### ISSUE TITLE
[Homework 2] 二進位 II

### ISSUE THREAD

**Issue by yihmnz** [coding-coworking-club/python-2019-fall#100]
## 提交連結
https://judge.ccclub.io/status/56be6e4f140393f8d14aa74ec1511c9d

## 程式碼

```python
def to_binary(n):
  n_2 = bin(int(n, 10))
  ans = []
  for t in range(2,len(n_2)):
    ans.append(int(n_2[t]))
  for a in range(len(ans)):
    if a < len(ans)-1:
      if ans[a] == ans[a+1]:
        ans[a+1] = 2
        if a != len(ans)-2:
          for x in range(2,len(ans)-a):
            if ans[a] == ans[a+x]:
              ans[a+x] = x+1
            else:
              break
  return ans
```

## 錯誤訊息
Wrong answer

## 問題描述
這題希望能夠把十進位轉成二進位，所以我用bin函式去轉換
先用一個for loop把bin轉出來的數字丟到ans的串列中(因為bin前面有0b 所以range從2開始)
再來是用for loop去比較相鄰的數字是否一樣
第一個if a < len(ans)-1 是防止index out of list
如果有一樣的數字 就把後面數值那個改成2
但因為這題需要累加
所以後面再跑一個for loop
先設一個條件if a != len(ans)-2 免得後面range爆掉
後面是想說從x = 2開始比較ans[a+x] 跟在ans[a]位置的數字是否相同 如果相同就改成x+1(累加)
如果出現ans[a+x] 跟在ans[a]位置不同的情況就break這個累加迴圈
期望可以變成這樣[1,1,1,1,0,0,1,0,1] ->[1,2,3,4,0,2,1,0,1] 
我在jupyter上輸出目前沒什麼問題
16會變成[1,0,2,3,4]
輸入提示的input也都正常
但是不知道問題出現在哪裡~~
請助教解惑 謝謝!

**Comment by hyusterr** [comment]
剛剛看了一下，你應該是連範例測資都沒有過喔，可以再看一下 hint 的敘述喔~
111100101
應該是轉為
[1, 4, 0, 2, 1, 0, 1]
喔~

**Comment by yihmnz** [comment]
## 修正後結果(還是錯誤)
https://judge.ccclub.io/status/1d2efd18c66b09b9b188e972be20d874
修正過後還是wrong answer
這次寫的程式丟16 出來是[1,0,4]
題目雖然理解對了 但不知道為何還是錯誤QQ

## 程式碼
```python
def to_binary(n):
  n = str(n)
  n_2 = bin(int(n, 10))
  ans = []
  for t in range(2,len(n_2)):
    ans.append(int(n_2[t]))
  for a in range(len(ans)):
    if a < len(ans)-1:
      if ans[a] == ans[a+1]:
        ans[a] = "NO"
  count = 1
  ANS = []
  for i in range(len(ans)):
    if ans[i] != "NO":
      ANS.append(ans[i])
      if count != 1:
        ANS.append(count)
        count = 1
    else:
      count += 1
  return ANS
```
## 邏輯描述
關於"NO"的調整
我是把[1,0,0,1,1,0,0]有重複的前一個改成"NO" 
所以雖然很怪(但我自己能理解)上面那個會變成[1,"NO",0,"NO",1,"NO",0]
再來用下面的迴圈去計算"NO"連續出現的次數
如果沒有"NO"就append到新的串列中
有的話就count +=1 如果停止連續的話就append(count)後 把count再次定回1
所以新的就會變成[1,0,2,1,2,0,2]
其中的2 都是用append(count)進去的
請助教再次幫我解惑QQ

**Comment by StevenChen1203** [comment]
這題的測資也有錯啊，input根本不是題目寫的那樣==

**Comment by yihmnz** [comment]
這題測資好像已經修正了~~
剛剛丟發現沒問題了
謝謝助教們~!
