### ISSUE TITLE
[General] Jupyter Notebook connecting to kernel

### ISSUE THREAD

**Issue by hyusterr** [coding-coworking-club/python-2019-fall#101]
## 錯誤訊息

![image](https://user-images.githubusercontent.com/52968111/66364358-f203c400-e9bb-11e9-9271-b9d93094b659.png)

## 問題描述

Jupyter Notebook 突然壞掉了，向大家求救 ><，Google 大部分說都是要把 ternado downgrade，但我已經照作了卻是無法解決。
在想可能是 Jupyter 找不到 ipython kernel 的問題，因為我 python 裝在 D 槽，但不知道要怎麼改路徑或是哪個檔案是 ipython kernel，求救~

**Comment by hyusterr** [comment]
嗚嗚霸托求救

**Comment by oscarcyhsu** [comment]
你要不要用我MLCC那個裝虛擬環境的方法看看

**Comment by alexypdu** [comment]
@hyusterr 解決了嗎？

**Comment by sc090410** [comment]
他說重開機就好了吧我記得
