### ISSUE TITLE
[General] 9-1、9-2 觀念上問題

### ISSUE THREAD

**Issue by gg0925** [coding-coworking-club/python-2019-fall#103]
## 程式碼

```python
s=input().split()

def sum_sort(s):
    sum=0
    for i in s:
        sum+=int(i)
    return sum

s=sorted(s,key=sum_sort)

c=list(map(int,s))
print(c)




s=input().split()
def reverse_str_sort(s):
    for i in range(len(s)):
        s_reverse=s[::-1]
    return s_reverse

def my_sort(s_sorted):
    s_sorted=sorted(s,key=reverse_str_sort)
    return s_sorted

print(my_sort(s))
```

## 錯誤訊息

不好意思~我想詢問一下關於for-loop的問題，
在9-1中 for i in s 表示是對"每一個串列內的字串"進行，
例如: 123 221 5  就是1+2+3=6，2+2+1=5，5
但9-2的問題中，
for i in range(len(s)) 則是對"整個字串串列，裡面有多少個字串"進行，
例如範例中的 :apple btc python    len(s)=3
但如果要符合9-1的"對每一個串列內的字串進行"
不是應該是 len(s)=apple的長度、btc的長度、python的長度=5、3、6嗎?

就是我不太清楚，
甚麼時候def是針對串列中的每一字串
還是整個串列，這樣的問題，
昨天上課助教有提到，
但可能不太聰明，
所以不是說很理解，
一直是一種似懂非懂的感覺，
還麻煩助教解惑，
兩題的一般測試都有測出正確的結果，
但想搞懂這個問題，
謝謝~麻煩助教或各位高手同學了!

**Comment by oscarcyhsu** [comment]
for i in iterable:
這個iterable如果是string，那i就是裡面的字符
這個iterable如果是list，i就是list裡面的元素
跟def沒有關係喔

**Comment by gg0925** [comment]
了解了!謝謝學長!!
