### ISSUE TITLE
[General] 11-2：字串字典

### ISSUE THREAD

**Issue by Vivian-chen16** [coding-coworking-club/python-2019-fall#106]
## 提交連結

https://judge.ccclub.io/status/378cc68d6a14c1e58df75151614408aa

## 程式碼

```python
def str_dict(s):
    dic = {}
    for i in s:
        dic[i] = s.count(i)
    return dic
    
def mysort(s):
    s = s.lower()
    for i in s:
        if i in "abcdefghijklmnopqrstuvwxyz":
            continue
        else:
            s = s.replace(i, "")
    return s
    
mystr = input()
mystr = sorted(mysort(mystr))
for key, value in str_dict(mystr).items():
    print(key, value, end = " ")
```

## 錯誤訊息

Ｗrong Answer

## 問題描述

測試過大小寫, 混合數字等例子, 都可以跑出題目的要求, 不確定哪邊出錯了ＱＱ

思路：先將輸入內容去除數字，並按照字母序排好
最後把char出現次數放進字典並輸出key and value

**Comment by sc090410** [comment]
嗨我只有大概看了一下，你看一下是不是跟這個一樣的問題～
#98

**Comment by Vivian-chen16** [comment]
如果我有先sorting再放入dictionary的話 這樣應該會按照字母序排 嗎（？

**Comment by sc090410** [comment]
不會XD
你可以想像成你sorting的時候是把東西從袋子裡拿出來，在櫃子裡排好，但丟進dictionary裡面就會再通通丟回袋子裡面，所以再抽出來的時候一樣不會照順序

**Comment by Vivian-chen16** [comment]
哦哦哦哦！原來是這樣xd 那我有想法了
謝謝助教！！！
