### ISSUE TITLE
[Homework 2] 二進位

### ISSUE THREAD

**Issue by winnywu508** [coding-coworking-club/python-2019-fall#109]
## 提交連結

https://judge.ccclub.io/status/e1f5adb9bd593d8804af1cc4042c3a97

https://judge.ccclub.io/contest/28/problem/031202

## 程式碼

```python
a = int(input())
b = bin(a)
c = [int(num) for num in b.split()]

ans = []

def to_binary(n):
    
for i in c:
    if c[i] != c[i+1]:
        ans.append(i)
        return ans
    
print(n)
```

## 錯誤訊息

compile error

## 問題描述

不太確定為是麼跑不出來。請問我的obj在哪裡有放錯嗎？
我的想法是當i 不等於i+1的時候他才會append i進去ans這個list裡面

**Comment by hyusterr** [comment]
注意函式 ( def 以下 ) 的縮排喔~

**Comment by winnywu508** [comment]
a = int(input())
b = bin(a)
c = [int(num) for num in b[2:].split()]

def to_binary(n):
---- ans = []
---- for i in range(len(c)):
---- ---- if c[i-1] != c[i]:
---- ---- ---- ans.append(c[i])
---- return ans    
print(to_binary(c))

我改了一下縮排 
請問為時麼這樣ans沒有被append進去？

**Comment by winnywu508** [comment]
https://judge.ccclub.io/status/53037351a7f8357a128d76356a713ab2

def to_binary(n):  
    
    ans = list(bin(n))
    
    del ans[0]
    del ans[0]
    
    final = []    
    for i in range(len(ans)):
        if ans[i-1] != ans[i]:
            final.append(ans[i])
            final = [int(num) for num in final]
    return final  

a = int(input())
print(to_binary(a))

請問這樣為時麼會runtime error

**Comment by hyusterr** [comment]
> https://judge.ccclub.io/status/53037351a7f8357a128d76356a713ab2
> 
> def to_binary(n):
> 
> ```
> ans = list(bin(n))
> 
> del ans[0]
> del ans[0]
> 
> final = []    
> for i in range(len(ans)):
>     if ans[i-1] != ans[i]:
>         final.append(ans[i])
>         final = [int(num) for num in final]
> return final  
> ```
> 
> a = int(input())
> print(to_binary(a))
> 
> 請問這樣為時麼會runtime error

你稍微整理下程式碼區塊吧，然後注意縮排~

**Comment by hyusterr** [comment]
這一題只要實作函式就可以囉，不用自己弄輸入輸出

**Comment by winnywu508** [comment]
最後出來WA...但我覺得已經轉成數字list了...

final = [int(num) for num in final]

請問哪裡有寫錯嗎

**Comment by winnywu508** [comment]
def to_binary(n):   

    ans = list(bin(n))
    ans = ans[2:]
    
    final = []    
    for i in range(len(ans)):
        if ans[i-1] != ans[i]:
            final.append(ans[i])
            final = [int(num) for num in final]
    return final 

改成這樣還是不行

**Comment by jeffery12697** [comment]
我猜是return的東西要跟題目指定的 一樣

**Comment by winnywu508** [comment]
def to_binary(n):   

    lst = list(bin(n))
    lst = lst[2:]
    
    ans = []    
    for i in range(len(lst)):
        if lst[i-1] != lst[i]:
            ans.append(lst[i])
    ans = [int(num) for num in ans]
    return ans

print(to_binary(16))
print(to_binary(596350))

我的output:

print(to_binary(16))
print(to_binary(596350))

[1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]

功課的sample output:
[1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]

我把return改成 return ans看起來output的東西是一模一樣的.....但還是wrong answer...............

**Comment by winnywu508** [comment]
我知道我哪裡寫錯了：Ｄ
closed
