### ISSUE TITLE
[Homework 1] 數字相加

### ISSUE THREAD

**Issue by waynepenguin** [coding-coworking-club/python-2019-fall#11]
## 程式碼

```python
a = input()
b = a[0]
n = 1
m = 1
for c in a:
    b = b + a[n]
    n = n + 1
print(b)
```

## 錯誤訊息

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-16-935484517872> in <module>
      5 m = 1
      6 for c in a:
----> 7     b = b + a[n]
      8     n = n + 1
      9 print(b)

IndexError: string index out of range

## 問題描述

字串可以相加，為什麼在for裡面就不能?
我這邊是先定義b=a[0]
假設a=123
b會等於1
然後跑完第一次的for
第一串重新指定b = 1 + 2也就是12
然後n=2
下一次就變成
b 指定為 原本的12+[2]=123
不知道這樣寫哪裡錯

**Comment by sc090410** [comment]
以下是幾件事情：
⒈字串相加（串接）是沒有問題的，並不會因為在for loop裡面或外面而有不同的表現
⒉注意一下你的error message通常是比較好的開始解決問題方法，這裡寫的是imdex error，意即在取用index（此處是string的imdex）是出現了錯誤，index out of range指的是你使用了超過範圍（不存在在目前字串index範圍）的index，或許可以想一下在 n 這個變數的設計和for loop循環次數之間的關係

**Comment by waynepenguin** [comment]
謝謝，我知道我問題出在哪裡了，這樣n會多跑一個沒有東西的迴圈

**Comment by waynepenguin** [comment]
話說我第一題寫出來了，但是發現批改系統好像有個問題
就是我原本的寫法限定在只有1個空格的時候答案會符合，但是批改系統是accept
如下'
```python
a = input()
b = "a"
d = "a"
n = 0
for c in a:
    b = b + c
    n = n + 1
    if c == " ":
        a1 = int(b[1:])
        d = d + a[n:]
a2 = int(d[1:])

print(a1+a2)
```

**Comment by alexypdu** [comment]
中間的確只會有一個空格唷！另外這題其實沒有你寫得這麼複雜，可以嘗試看看 `.split()` 會更加簡單 😉

**Comment by waynepenguin** [comment]
原本忘記有split這個函式
所以前面用for if去寫
剛剛試著用split去寫發現原來這麼簡單(但這樣的寫法好像也是只限定在數字間只有一個空格)
但是有個疑問是
用split分開後輸出a會等於[a1,a2]
這邊的[]代表是甚麼意思?是矩陣還是什麼?
為什麼a的index會是a[0]等於空格前的數字串
a = input()
a = a.split(" ")
print(int(a[1])+int(a[0]))

**Comment by waynepenguin** [comment]
因為題目沒說只有一個空格@@

**Comment by alexypdu** [comment]
`.split()` 就算中間有很多空格也適用唷，你可以再 google 看看這個函式的用途或直接嘗試看看各種測資。另外你說的 `[]` 在 Python 中叫做 **串列**，是本週指定閱讀的內容。

**Comment by waynepenguin** [comment]
謝謝!!!大致知道split的運作方式了
然後剛剛的寫法把index 1改成-1就試用在多空格了
謝謝

**Comment by alexypdu** [comment]
```python
foo = 'a          b' # 中間有 10 個空格
foo_split = foo.split()
print(foo_split) # ['a', 'b']

# 使用 .split() 時不論中間有幾個空格都會被割掉，foo_split[0] = 'a'，foo_split[1] = 'b'
# 另外 foo_split[-1] 是取這個串列裡面倒數第一個元素，也就是 'b'，所以跟是不是多空格無關喔！

bar = 'x,y,z'
bar_split = bar.split(',')
print(bar_split) # ['x', 'y', 'z']

# .split() 括號中的參數可以指定分割符號來做字串切割，否則預設是以空白切割。
```
