### ISSUE TITLE
[General] 8-2：最長字串

### ISSUE THREAD

**Issue by Yi-chunChang** [coding-coworking-club/python-2019-fall#110]
## 程式碼

```python
def longest_str(L):
    length=[]
    for i in range(len(L)):
        length_i=int(len(L[i]))
        length.apped(length_i)
    longest_index=length.index(max(length))
    return longest_index
List=input()
slist=List.split(" ")
print (slist[longest_str(slist)])
```

## 錯誤訊息

AttributeError                            Traceback (most recent call last)
<ipython-input-64-91e8fc170286> in <module>
      8 List=input()
      9 slist=List.split(" ")
---> 10 print (slist[longest_str(slist)])

<ipython-input-64-91e8fc170286> in longest_str(L)
      3     for i in range(len(L)):
      4         length_i=int(len(L[i]))
----> 5         length.apped(length_i)
      6     longest_index=length.index(max(length))
      7     return longest_index

AttributeError: 'list' object has no attribute 'apped'
#可是這部分先前就成功append資料在list中，所以不知道這裡哪裡有問題

## 問題描述

我想先建構一個儲存每一個字串中文字的長度的字串，然後找出最長字串的位置，
讓函數回傳該字串位置，然後輸出。
但一直出現attribute error，不清楚哪裡出了問題。

**Comment by alexypdu** [comment]
請注意應選擇 `general` 分類及標題喔。

**Comment by alexypdu** [comment]
注意看錯誤訊息會發現，你的第五行打錯了。

``` python
length.apped(length_i) # <--- 是 append 不是 apped
```

**Comment by Yi-chunChang** [comment]
厄。。。太蠢惹。。。
感謝助教！
