### ISSUE TITLE
[Week 5] 小明去爬山

### ISSUE THREAD

**Issue by alemapnil** [coding-coworking-club/python-2019-fall#111]
## 程式碼

```python
# 請把程式碼填在這！
```

## 問題描述
這一題思路頗複雜，可否給我一些提示，謝謝

**Comment by hyusterr** [comment]
剛剛稍微看了一下題目，我覺得作法可能可以是這樣的
1. 把 input 好好的吃進來，每條步道的資料各存 `list of list` (當然其他的資料結構也可以)
2. 判斷每條步道有沒有符合小明肥宅條件1、2，如果不符合，就把該步道剔除，這裡可以分兩階段判斷，第一階段判斷涼亭是不是符合要求，第二階段判斷廁所是不是符合要求；把符合的步道納入一個候選名單裡
3. 篩選過後剩下的步道裡，按照爬升高度排序，輸出小明最可能喜歡的那條；如果到這個階段就沒有步道剩下了，那就叫小明乖乖待在家
