### ISSUE TITLE
[Homework 2] 小明去爬山

### ISSUE THREAD

**Issue by graceyfchang** [coding-coworking-club/python-2019-fall#113]
## 提交連結

https://judge.ccclub.io/status/c62cfa3907c2c02b9fee9fe0021dbc9d

## 程式碼

```python
def outcome(lists):

    rest_list = []
    toilet_list = []

    for i in range(len(lists)):
        if lists[i][1]  == 'True':
            rest_list.append(i)
        if lists[i][2]  == 'True':
            toilet_list.append(i)
    
    if len(lists) < 4:
        return True
    else:
        if len(rest_list) != 0 and len(toilet_list) != 0:
            for i in range(len(rest_list) - 1):
                if rest_list[i + 1] - rest_list[i] > 3:
                    return False
            for i in range(len(toilet_list) - 1):
                if toilet_list[i + 1] - toilet_list[i] > 3:
                    return False
            if (rest_list[0] > 2) or (len(lists) - rest_list[-1] > 3) or (toilet_list[0] > 2) or (len(lists) - toilet_list[-1] > 3):
                return False
            else:
                return True
        else:
            return False
```

## 錯誤訊息

批改系統寫Runtime Error，但我想可能是def裡面的邏輯有誤，所以只貼def的程式碼過來。

## 問題描述

主要想問題目的邏輯，想確認我這個def是不是有寫對。

lists代表該路線的所有資訊，例如範例一
lists = [['30', 'True', 'True'], ['3', 'False', 'False'], ['0', 'True', 'True'], ['3', 'True', 'True'], ['-5', 'False', 'True'], ['1', 'False', 'False'], ['10', 'True', 'True'], ['0', 'False', 'False'], ['5', 'False', 'False'], ['-3', 'False', 'False'], ['2', 'False', 'True'], ['-1', 'False', 'False']]。
先把有涼亭(rest)及廁所(toilet)的據點轉成另外的list，例如上方的例子可以轉成
rest_list = [0, 2, 3, 6]
toilet_list = [0, 2, 3, 4, 6, 10]

需要確認題目邏輯的部分：
1. 如果lists的len < 4，則此路可走
2. 如果lists的len >= 4，且整路皆無涼亭/廁所(即len(rest_list)=0或len(toilet_list)=0)，則此路不可走
3. 如果lists的len >= 4，且兩個涼亭/廁所的距離大於300m，則此路不可走
4. 如果lists的len >= 4，且起點到第一個涼亭/廁所大於300m(即rest_list[0]>2或toilet_list[0] >2)，則此路不可走
5. 如果lists的len >= 4，且最後一個涼亭/廁所到終點大於300m(即len(lists) - rest_list[-1] > 3或len(lists) - toilet_list[-1] > 3)，則此路不可走
6. 不符合以上2-5的情況，則此路可走

再麻煩助教幫忙解答，謝謝!!!

**Comment by oscarcyhsu** [comment]
長度=3然後完全沒廁所也不行走
Runtime error應該是list取用index到超過長度的地方

**Comment by graceyfchang** [comment]
我懂了，解出來了，謝謝~~
