### ISSUE TITLE
[Homework 2] 二進位

### ISSUE THREAD

**Issue by lss19920912** [coding-coworking-club/python-2019-fall#114]
## 提交連結

https://judge.ccclub.io/status/4bf49421ffd492f86eb082f2eb9c1bba

## 程式碼

```python
n = int(input())
n_binary= bin(n).replace('0b', '')
n_binary_split= list(n_binary)

b=[]
b.append(int(n_binary_split[0]))

for i in range(1, len(n_binary_split)) :  
    if n_binary_split[i] != n_binary_split[i-1]  :
        b.append(int(n_binary_split[i]))
print(b)
```

## 錯誤訊息

runtime error

**Comment by hyusterr** [comment]
其實你已經寫得差不多了，但題目的要求是要包成函數ㄛ~
寫成函數應該就差不多了

**Comment by lss19920912** [comment]
> 其實你已經寫得差不多了，但題目的要求是要包成函數ㄛ~
> 寫成函數應該就差不多了
助教您好，我改成函式還是runtime error

#二進位
def to_binary(n) :
    return bin(n).replace('0b', '')

a = int(input())
a_binary = to_binary(a)
a_binary_split = list(a_binary)

b=[]
b.append(int(a_binary_split[0]))

for i in range(1, len(a_binary_split)) :  
    if a_binary_split[i] != a_binary_split[i-1]  :
        b.append(int(a_binary_split[i]))
print(b)
