### ISSUE TITLE
[Homework 2] 助教業績統計

### ISSUE THREAD

**Issue by alemapnil** [coding-coworking-club/python-2019-fall#117]
## 程式碼

```python
# 請把程式碼填在這！
```

## 問題描述
雖然系統接受我的程式碼，但我發現題目設計有誤，若不只一個助教擁有最高分業績，output依舊只能輸出一行，因為題目限制的關係。

**Comment by hyusterr** [comment]
@yang611 @Kevinweisl

**Comment by alexypdu** [comment]
如果有助教成績並列的話請輸出編號較小的。
