### ISSUE TITLE
[Homework 1] 字元數數

### ISSUE THREAD

**Issue by bidhead** [coding-coworking-club/python-2019-fall#12]
## 程式碼

```python
key_in = input()
sentence = input()
lst = key_in.split(" ")
a=lst[0]
b=lst[1]
c=lst[2]
print(sentence.count(a),  sentence.count(b), sentence.count(c))
```

## 錯誤訊息

Wrong Answer

## 問題描述

我測試輸出的第一個範例得到：2 1 2
I am a idiot 有 2個a, 1個d, 2個i；但範例答案是 2 1 3
第二個範例得到：4 3 2；但範例答案是 4 4 2
我數了一下覺得我的答案應該才是對的......?還是我哪裡搞錯了，謝謝

**Comment by sc090410** [comment]
只要是同一個字母，大小寫都會計入～

**Comment by bidhead** [comment]
ok~~~我瞭解了XD

**Comment by sc090410** [comment]
那再麻煩你幫我按close issue～
