### ISSUE TITLE
[General] 'int' object is not iterable

### ISSUE THREAD

**Issue by QuintusZhan** [coding-coworking-club/python-2019-fall#124]
## 程式碼

```python
sales=input()

total_sales=[sum(int(i)) for i in sales.split(" ")]
total_sales
```

## 錯誤訊息

'int' object is not iterable

## 問題描述

我的input 要放2 2 2 ，不知道有無辦法可以得到 total_sales = 6的結果

**Comment by sc090410** [comment]
`sum`這個 function 只能用在「iterable 可以遍歷」的資料型態上面：像是list這種。
所以你不應該是去`sum(int(i))` ，而是應該要sum這整個list
