### ISSUE TITLE
[Homework 1] 字元強調

### ISSUE THREAD

**Issue by KuangChen-Chen** [coding-coworking-club/python-2019-fall#13]
## 程式碼

```python
enfasis = input()
sentence = input()
sent_split = sentence.split(" ")
enfa_up = enfasis.upper()
text=""
for i in range(0,len(sent_split)):
    text = text+ " " + sent_split[i][0].replace(enfasis, enfa_up)+sent_split[i][1::]
print(text)
```

## 錯誤訊息

![Screenshot 2019-09-19 at 09 57 46](https://user-images.githubusercontent.com/55127860/65207352-f1b29000-dac3-11e9-80ed-74b28cc4c195.png)

![Screenshot 2019-09-19 at 09 58 28](https://user-images.githubusercontent.com/55127860/65207379-0d1d9b00-dac4-11e9-82b5-77894525b87f.png)
## 問題描述

思路是輸入一個要強調的字、一個要改的句子，把句子切割成list，把list中每個element中的第一個index，如果是要強調的那個字，取代成大寫。
用Jupyter 跑兩個範例都沒問題，交作業則一直出現wrong answer，不知道如何debug><

**Comment by alexypdu** [comment]
你的輸出最前面會多一個空格 👀

**Comment by KuangChen-Chen** [comment]
！！！！  感謝～～～～ 解決了
