### ISSUE TITLE
[Homework 1] 字元數數

### ISSUE THREAD

**Issue by KuangChen-Chen** [coding-coworking-club/python-2019-fall#14]
## 提交連結

e78f5eb4b87d

## 程式碼

```python
a = input()
b = input()
a = a.split(" ")

output =  str(b.count(a[0])) + " " + str(b.count(a[1])) + " " + str(b.count(a[2])) 

print(output)
```

## 錯誤訊息

![Screenshot 2019-09-19 at 10 35 19](https://user-images.githubusercontent.com/55127860/65208970-31c84180-dac9-11e9-8f92-36227908aefa.png)
## 問題描述

問題：為什麼我測第一個範例時，i會少算一個，測第二個範例時，s會少一個？
思路：很單純依據三個去算他的數量，最後輸出成一組字串

**Comment by alexypdu** [comment]
下次提交連結要付超連結而不是單純流水號唷！然後如果自己發現問題的話也可以留言讓大家知道，說不定其他人也會碰到類似的困惑 😉
