### ISSUE TITLE
[Homework 2] 小明去爬山

### ISSUE THREAD

**Issue by yhchang1** [coding-coworking-club/python-2019-fall#140]
## 提交連結

https://judge.ccclub.io/status/5b74ac7da20081d946efda5281aa84c3

## 程式碼

```python
# 請把程式碼填在這！
```

## 錯誤訊息

runtime error

## 問題描述

因為程式碼較長，想法直接加註在提交連結內了~
試過sample和自己代幾個例子都沒問題，
想請助教提示一下我的runtime error可能是出現在什麼情況下
謝謝助教，麻煩了！

**Comment by sc090410** [comment]
是IndexError喔
```
IndexError: list index out of range
```

**Comment by yhchang1** [comment]
> 是IndexError喔
> 
> ```
> IndexError: list index out of range
> ```

那想請問可能會是什麼情況下的indexerror~~
因為我試過如果只有少數據點(例如1個或兩個而已)或是只有少數路線都是沒問題的，不知道問題出在哪QQ
謝謝助教！
