### ISSUE TITLE
[Week 6] 幾連霸

### ISSUE THREAD

**Issue by alemapnil** [coding-coworking-club/python-2019-fall#146]
## 程式碼

```python
# 請把程式碼填在這！
```

## 問題描述
我看不太懂題目的意思，Input 1 2 3 4 5 6 7 8，不是遞增七次嗎? 連續加1七次，為何output是8 ?
input 1 2 3 5 6 7 8，為何是遞增四次，從何看出?
麻煩助教解釋一下，謝啦~

**Comment by oscarcyhsu** [comment]
沒有遞增的話 算連續一次
1是一次
12是兩次
123是三次

**Comment by alemapnil** [comment]
那麼 1 2 3 5 6 7 8，為何是遞增四次?

**Comment by oscarcyhsu** [comment]
123是三次
5678是四次
4>3 取4為答案

**Comment by alexypdu** [comment]
最長遞增連續子序列的長度。

**Comment by alemapnil** [comment]
有規定遞增一定要是加1嗎?

**Comment by alexypdu** [comment]
以數學上的定義來說是沒有，但我們的題目是規定要 + 1 才算。

**Comment by alemapnil** [comment]
有規定數字不能重複出現嗎?

**Comment by alemapnil** [comment]
我試了好幾種可能，答案都正確，為何系統不接受??
https://judge.ccclub.io/status/99daeb9b775da153333e02a1c5c30a66

思路是後項比前項加1，就增加後項到列表一中，若後項非前項加1，將列表一的列表新增至列表二，再將列表一清除，進行下一迴圈。最後列表二中已經累積連續遞增的列表，挑選最長串列表(亦即遞增次數最多)，計算其長度len()，再將長度加一，表示真正遞增次數。長度加一原因是，連續遞增數字的第一項要算入。

**Comment by alemapnil** [comment]
https://judge.ccclub.io/status/ebb7a21c439dfd09aebb08c5053c9993

考慮只有一個數字，與全都不連續遞增的情況 ，而作修改，為何還不行?

**Comment by alemapnil** [comment]
沒有遞增的話 算連續一次....
我成功了
