### ISSUE TITLE
[Homework 1] 字元數數

### ISSUE THREAD

**Issue by chihyunhung** [coding-coworking-club/python-2019-fall#15]
## 提交連結
https://judge.ccclub.io/status/d0ddd9967914cdc288050b5f23b65324

## 程式碼

```python
test = input()
w = input()
test_upper = test.upper()
test = test.split(" ")
test_upper = test_upper.split(" ")
test = test + test_upper

number = str(w.count(test[0])+w.count(test[3])) + " " + str(w.count(test[1])+w.count(test[4])) + " " + str(w.count(test[2])+w.count(test[5]))
print (number)
```

## 問題描述
先創造大寫的list,input與大寫list分別split後相加, 將同字母大小寫count加在一起,在jupyter成功但在judge系統失敗

**Comment by sc090410** [comment]
嗨嗨～是我們的測資稍微有一點小小的bug，目前已經修好了應該會過～
原因是你的`string.split(" ")`的寫法正好會踩到「當input的第三個字母最後面不小心多打了一個空格，會讓切出來的list多出一個**空字串**的element」，但如果寫`string.split()`的話剛好不會，建議你可以自己在jupyter notebook上面試試看，應該會清楚一點～

**Comment by chihyunhung** [comment]
謝謝助教！我剛用string.split(" ")在judge系統上還是wrong answer,但改了string.split() jupyter跟judge都沒問題了！謝謝
