### ISSUE TITLE
[Homework 1] 字元數數

### ISSUE THREAD

**Issue by QuintusZhan** [coding-coworking-club/python-2019-fall#16]
## 提交連結

https://judge.ccclub.io/status/575310ed2b7e9e94d861d8e3e38daf70

## 程式碼

```python
s=input()
targets=s.split(' ')
sentence=input().lower()


for target in targets:
    n=0
    for i in sentence:
        if i == target:
            n += 1
    print(n, end=' ')
```

## 錯誤訊息

Wrong Answer

## 問題描述

都可以得到sample output，自己試試其他的句子也都行得通，但還是無法過關。

**Comment by sc090410** [comment]
這樣輸出的話，輸出最後一個字母的後面會有空白對吧！但我們不要空白～
