### ISSUE TITLE
[General] 9-2：字串反轉排序

### ISSUE THREAD

**Issue by Thomas-Ke** [coding-coworking-club/python-2019-fall#160]
## 提交連結
https://judge.ccclub.io/status/ed61cb552dd67b3b5506b7887f853d2f

## 程式碼

```python
# 請把程式碼填在這！
a=input().split()
for i in a:
    a=sorted(a, key=i[-1])
    print(a)
```

## 錯誤訊息
Runtime error

## 問題描述
將串列a中的字串取出，並按照字串中的最後一個字元排序

**Comment by kemerical** [comment]
題目是要求輸出  依據 list 裡面的字串 "反轉" 後排序的結果，你的寫法應該沒辦法滿足題目所需呦，可以想想看如何擅用 slicing 跟 sorted 。另外，可以參考下面的錯誤訊息：
```
'str' object is not callable
```
