### ISSUE TITLE
[Homework 3] 完全平方數 II

### ISSUE THREAD

**Issue by waukin** [coding-coworking-club/python-2019-fall#176]
## 提交連結

https://judge.ccclub.io/status/de48a7fe123c1e50ae9fde6d2ad25eed

## 程式碼

```python
import math

#input 2 numbers, a and b, a <= b
lst = [int(i) for i in input().split()]
a = lst[0]
b = lst[1]

if a < 0:
    a = 0
else:
    pass

#set a counter and a starting point
count = 0
start = math.sqrt(math.ceil(a))
while  a <= start ** 2 <= b:
    count += 1
    start += 1
print (count)
```

## 錯誤訊息

Wrong Answer

## 問題描述

1. 按照問題的敘述，輸入兩個值，第一個為a;第二個為b，且a<=b。
2. 因為a比較小，當a小於零時，直接將a 指定為0。
3. 利用math模組內的sqrt函數算出a的平方根值。
4. 利用math模組內的ceil函數將a的平方根值無條件取整數進位。
5. 再利用while迴圈累加計算出總共有幾個完全平方數。
Jupyter上跑出的結果是正確的，不知道是不是有什麼邊界條件沒考慮到，請助教指點，謝謝。

**Comment by alexypdu** [comment]
Try `24 25`.

**Comment by waukin** [comment]
懂了~~謝謝助教
