### ISSUE TITLE
[Homework 3] 完全平方數 II

### ISSUE THREAD

**Issue by alemapnil** [coding-coworking-club/python-2019-fall#177]
## 程式碼

```python
s=input()
s=s.split(' ')
s=[int(i) for i in s]
s=sorted(s)
x,y=s

pos=[i for i in range(x,y+1) if i>=0]
ans=[]
    
for i in pos:
    if (i*i) in pos:
        ans.append(i*i)
print(len(ans))
```

## 問題描述
我算都正確，為何系統說不行?

**Comment by alemapnil** [comment]
@Kevinweisl @sc090410 @alexypdu @yang611 @hyusterr  請助教替我解惑，麻煩了

**Comment by alexypdu** [comment]
Try this one: `4 9`.

**Comment by alemapnil** [comment]
我改了程式碼，答案也都對，為何還是不行?  還有Time Limit Exceeded的錯誤是甚麼意思?

https://judge.ccclub.io/status/62f961c4ff8ec8d440c3d522cdf0ca13

**Comment by alemapnil** [comment]
@alexypdu 我試了其他方式，降低記憶體容量，但時間還是太長，要怎麼做才能過的了??

https://judge.ccclub.io/status/d68563f0c05d935f0dae052ad0e09124

**Comment by alexypdu** [comment]
這題不需要 import module，另外提示是 `** 2` 會比 `** 0.5` 快。

**Comment by alemapnil** [comment]
其實現在就只差程式碼跑不夠快而已，我都用產生器試了，為何還是不行?  可否告知解方的方向? 

https://judge.ccclub.io/status/571b4734fe28cfbdeb045aec2768481c

不用 i**0.5，也還是不行!  究竟要如何，請助教給方向
https://judge.ccclub.io/status/a90c5b728cc643b067c13a1928c64cdb

**Comment by alexypdu** [comment]
```python
s=input()
s=s.split(' ')
s=[int(i) for i in s]
x,y=s

s=[i for i in range(x,y+1) if i>=0] # <--- 這邊創造 list 會消耗記憶體，如果 a, b 差很多會 MLE

count=0

for i in range(y+1):
    if i*i in s: # <--- 判斷 i ** 2有沒有在串列中來推論該數是否落在 a, b 之中是可行，只是太慢
        count+=1


print(count)
```

你想一下，你只是要判斷一個數字有沒有被另外兩個數字夾住，真的需要一個串列加上 `in` 嗎？

**Comment by Kevinweisl** [comment]
看了一下你的程式，你產生了一個 list 裡面是 a~b 所有的非負整數
可以試著想看看這個 list 是否有存在的必要？

補充： `in` 這個語法 python 背後實作其實是幫你在 list 中跑一次 for loop，效率其實並不是太好（因此才會請你可以思考看看 list 是否有存在的必要

**Comment by alemapnil** [comment]
沒有list也還是不行，可否透漏一些線索也好，思考脈絡也好，謝謝

https://judge.ccclub.io/status/ca1c993b15e8c5afde27e4bde65dd0cc

**Comment by alemapnil** [comment]
知道解方了  真的滿賊的
