### ISSUE TITLE
[Week 7] Three sum 趴兔

### ISSUE THREAD

**Issue by yihmnz** [coding-coworking-club/python-2019-fall#179]
## 提交連結

https://judge.ccclub.io/status/365998f95368bbcec96ee7f69b4dad1b

## 程式碼

```python
I = [int(i) for i in input().split(" ")]
k = int(input())

import itertools
s = list(itertools.combinations(I,3))
S = [sum(i) for i in s]
S.sort()
for t in S:
    if t < k:
        count += 1
    else:
        break
print(count)
```

## 錯誤訊息

Time Limit Exceeded

## 問題描述

系統上顯示跑了200 ms
但是卻說超過時間
因為我之前課堂練習時寫迴圈去試會到兩秒多
所以我想說改用combination再去算總和~
想請問助教這題可以怎麼解呢~~謝謝

**Comment by alexypdu** [comment]
利用 **itertools**  模組產生所有組合背後其實會有三個 for-loop，時間會跟串列長度的立方成正比，我們設計這題的時間限制就是要擋住這種做法，再想想其他方式吧！

**Comment by alexypdu** [comment]
Duplicate of #182.
