### ISSUE TITLE
[Homework 1] 字元數數

### ISSUE THREAD

**Issue by feianan** [coding-coworking-club/python-2019-fall#18]
## 提交連結

https://judge.ccclub.io/status/4b98195358f7c7fe24925b29165df9a6

## 程式碼

```python
a = input()
b = input()

sen = b.split()
num = len(sen)
i = 0

for i in range(0,num+1):
    for word in sen:
        if a == sen[i][0]:
          sen[i][0] = a.upper()
    i += 1

print (sen)
```

## 錯誤訊息

Runtime Error

## 問題描述

先把句子做成串列，找串列中每個字串的第一個字元有沒有符合a這個字元，並指定它為大寫。在Jupyter Notebook裡面的錯誤訊息是描述說不能指定字串('str' object does not support item assignment)，不知道能換什麼邏輯去想這題Ｑ

**Comment by sc090410** [comment]
嗨嗨～這裡的問題就是string的性質了！不同的data type「可以更改」的程度是不一樣的，就像上課說的，我們通常是用一個變數指向一個物件，字串這種物件你不能夠“更改字串的內容”，只能讓變數“指向一個新的字串”，這就是'str' object does not support item assignment要告訴你的意思（這就是在討論mutable跟immutable的差別，更詳細的解釋可以參照 http://wsfdl.com/python/2013/08/14/%E7%90%86%E8%A7%A3Python%E7%9A%84mutable%E5%92%8Cimmutable.html ）

**Comment by alexypdu** [comment]
```python
for i in range(0,num+1):
    for word in sen: # <--- 事實上這第二層的迴圈是沒有必要的
        if a == sen[i][0]:
          sen[i][0] = a.upper() # <--- 如同 @sc090410 所說我們沒辦法直接修改字串
    i += 1
```

雖然沒辦法直接修改字串，但可以重新創造一個符合需求的字串並指定給其他變數，最後再拼湊出你要的答案。

樓上 @sc090410 貼的文章是比較偏向語言特性，但瞭解它們有助於後續的學習唷！
