### ISSUE TITLE
[Homework 3] 完全平方數 II

### ISSUE THREAD

**Issue by heyiamstella** [coding-coworking-club/python-2019-fall#180]
## 提交連結

https://judge.ccclub.io/status/bd32f2eab1b0f1d4fc8e8ae690e519c6

## 程式碼

```python
# 請把程式碼填在這！
a=input()
b=a.split(" ")
c=int(b[0])
d=int(b[1])
count=0
if c<0 and d<0:
    count=0
elif c<=0 and d==0:
    count=1
elif d>0:
    for i in range(0,d+1):
        if i**2>=c and i**2<=d:
            count+=1
print(count)
```

## 問題描述

測資有過，有試過幾組測資也是對的，再麻煩助教謝謝!!

**Comment by alexypdu** [comment]
請提供提交連結。

**Comment by heyiamstella** [comment]
@alexypdu 連結已更新 謝謝助教

**Comment by alexypdu** [comment]
你的程式碼跑不夠快，提示請參考 https://github.com/coding-coworking-club/python-2019-fall/issues/177#issuecomment-545465751

**Comment by heyiamstella** [comment]
@alexypdu 已有設法讓程式更為有效率但還是Time Limit Exceeded(已更新程式與連結)
想請問助教能否再給一些方向?
非常感謝助教的幫忙

**Comment by alexypdu** [comment]
最後的 for-loop 應該可以適當地 break？

**Comment by heyiamstella** [comment]
謝謝助教
