### ISSUE TITLE
[Week 7] 連四相乘

### ISSUE THREAD

**Issue by alemapnil** [coding-coworking-club/python-2019-fall#181]
## 程式碼

```python

```

## 問題描述
題目限制時間1000ms, 我才136ms, 為何說我程式耗時過久?

**Comment by alexypdu** [comment]
提交連結？

**Comment by alemapnil** [comment]
https://judge.ccclub.io/status/af62595b75b87794b89974b351ccfbe2

**Comment by alexypdu** [comment]
1. 請忽略你看到的 136 ms，那個不是真正執行的時間（你們看不到）。
2. 你把所有組合都算一遍這件事本身會很慢是正常的，這題算有點腦筋急轉彎，再想想吧。
3. 某個測資下你目前的 code 會 **Runtime Error**。
4. 寫題目盡量不要 import module，除非我們明確要求你。

**Comment by alemapnil** [comment]
方便透露一下腦筋急轉彎的思考方向嗎？

**Comment by alexypdu** [comment]
會出現最大值的組合只有幾種可能而已。

**Comment by alemapnil** [comment]
我算出來了
