### ISSUE TITLE
[Week 7] Three sum 趴兔

### ISSUE THREAD

**Issue by alemapnil** [coding-coworking-club/python-2019-fall#182]
## 程式碼

```python
import itertools as it

s=input()
s=s.split(' ')
s=[int(i)for i in s]

n=int(input())

a=it.combinations(s,3)
a=list(a)

count=0
for i in a:
    if sum(i)<n:
        count+=1
print(count)
```

## 問題描述
算都對，哪裡出錯?

**Comment by alexypdu** [comment]
See https://github.com/coding-coworking-club/python-2019-fall/issues/179#issuecomment-545857523.

**Comment by alemapnil** [comment]
一般想法是得知串列的排列組合總和，再將總和小於n的組合挑出，若助教將itertools擋住，就是不要我們用此方法解題，也不要用三個for loop解題，請問還有甚麼方法可以解題的，思路邏輯為何? 方便提供方向嗎? @alexypdu THX.

**Comment by alexypdu** [comment]
提示是：輸入的數列是排序過的。

**Comment by alemapnil** [comment]
不用itertools，也限制迴圈迭代所有元素的情況了，但還是超過時間，究竟還有啥方法?  助教是希望我們用什麼邏輯解題? @alexypdu

https://judge.ccclub.io/status/19058bb00cac1143ac19cbd99efe44a9

**Comment by alexypdu** [comment]
Don't rush.

這題本來難度就比較高（有 TLE 的限制），所以沒有設計成作業。同學們在自己電腦上測了範例測資通過後上了 judge 沒過本來就是很常見的事情，助教也理解。希望同學們能透過思考及查資料，慢慢抽絲剝繭找到最終的解答，過程中助教們也能給予適當適量的線索。

以這題來說，即使你再怎麼追問，助教能給的線索也就這些了。剩下未解的部分請你跟同學們討論，或是嘗試 google 後自行解答吧。

P.S. 當然如果你有新的想法還是歡迎留言跟我們討論。
