### ISSUE TITLE
[Homework 3] 完全平方數 II

### ISSUE THREAD

**Issue by Tkkjie** [coding-coworking-club/python-2019-fall#183]
## 提交連結
https://judge.ccclub.io/status/e1b42de3d5416a9e987873ff529cf048

## 程式碼

```python
# 請把程式碼填在這！
num=[int(n)for n in input().split()]
a,b=num
count=0

if a<=0:
    for i in range(0,b+1):
        c=i*i
        if  c>b:
            break
        elif c>=a  and c<=b:      
               count+=1
            
else:
    for i in range(a,b+1):
        c=i*i
        if  c>b:
            break
        elif c>=a  and c<=b:      
            count+=1

print (count)
```

## 錯誤訊息

Wrong Answer

## 問題描述

在Jupyter上嘗試過幾個測資都正確，但Judge還是不通過，不知道是什麼狀況沒考慮到？
我的思路是：
1）a<=0 的話就直接從0開始跑for loop。
2）用一個變數c來接住平方數，平方數只要超過b就直接break。如果平方數比b小就讓count +1。
3）Else, a>0 就用一樣的方式跑For loop。
4）print 出count的答案。

先謝謝助教解惑～

**Comment by alexypdu** [comment]
試試看 `9 16`，感覺你題意沒有弄清楚唷～
