### ISSUE TITLE
[Homework 3] 揪狼殺

### ISSUE THREAD

**Issue by Eric03690** [coding-coworking-club/python-2019-fall#187]
## 提交連結

https://judge.ccclub.io/status/96244d22684deed160bc723e82db5acf

## 程式碼

```python
# 請把程式碼填在這！

s = int(input())
lst = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
dic1 = {}
mink = 25
num = 0

for k in range(s):
    time = input().split(" ")
    for k in time:
        lst[int(k)] += 1

for k in range(len(lst)):
    if lst[k] >= 12:
        num += 1
        if k <= mink:
            mink = k
            dic1[mink] = num
        if k > mink:
            dic1[mink] = num
    if lst[k] < 12:
        num = 0
        mink = 25

if dic1 == {}:
    print(lst.index(max(lst)))
else:
    maxi = max(dic1, key=dic1.get)
    print(maxi)
```

## 錯誤訊息

Wrong Answer

## 問題描述

目前測試過範例中的測資都有通過
不確定問題出現在哪裡
思路如程式碼中註解
謝謝!!

**Comment by Kevinweisl** [comment]
請問有提交連結嗎？麻煩補上方便助教幫忙解惑。

**Comment by Eric03690** [comment]
不好意思，連結如下：https://judge.ccclub.io/status/c17182f9b65cce6b508de7aa4c27aa1c

**Comment by Kevinweisl** [comment]
還記得我們課堂說的，dict 的是沒有順序的這件事嗎？
檢查一下你的 code ，找一下哪邊有問題吧！

備註：
python 3.7 後的 dictionary 是有順序的，在那之前是沒有的
Reference: naftaliharris/tauthon#86

**Comment by Eric03690** [comment]
因為中間有將字典換成list，想請問這樣轉換之後list也會沒有順序嗎？
剛才將dict拿掉了，但仍舊無法通過QQ

**Comment by Peterorr** [comment]
能否再附上新的提交連結，讓助教幫你確認？

**Comment by Eric03690** [comment]
上述文章中的連結已經更新過了
連結如下，謝謝！
https://judge.ccclub.io/status/96244d22684deed160bc723e82db5acf

**Comment by yeutong** [comment]
嗨～一樣還是要小心 dict 的順序問題噢！想想看如果有兩個超過十二人有空的連續時間長度相同會怎麼樣呢～

**Comment by Eric03690** [comment]
將字典完全去掉後已成功，謝謝！
