### ISSUE TITLE
[Homework 3] 完全平方數 II

### ISSUE THREAD

**Issue by kristy30736** [coding-coworking-club/python-2019-fall#192]
## 提交連結

https://judge.ccclub.io/status/f5c6298b4bc7a92588fbc5a3b0f642b4

## 程式碼

```python
a=int(input())
b=int(input())

square = [ ] 

for i in range(0,b+1): 
    if a <= i*i <= b: 
        square.append(i*i)
    elif i*i < a:
        continue
    elif i*i > b:
        break

print(len(square))
```

## 錯誤訊息

Runtime Error

## 問題描述

jupyter notebook上測資都正確但顯示runtime error
有點不知道哪邊需要修正

思路如下:
1. 設一個空串列square存放平方數字
2. 用for loop在0到b的範圍內逐一檢視i平方是否在a和b之間
    若i平方<a則continue、介於a與b之間則將值存入square串列，直到>b時結束迴圈
3. 印出square的串列長度

感謝助教!!

**Comment by Peterorr** [comment]
題目只會給一行 input 喔！
和你的程式不相符，請修改一下！

**Comment by kristy30736** [comment]
喔喔喔沒注意到XDDD
感謝助教我再修改一下～～
