### ISSUE TITLE
[Homework 3] 完全平方數 II

### ISSUE THREAD

**Issue by YuchiWang621** [coding-coworking-club/python-2019-fall#194]
## 提交連結

題目：https://judge.ccclub.io/contest/33/problem/031302
錯誤程式碼：https://judge.ccclub.io/status/662cb39ed00b871168b26013cf36f15d

## 程式碼

```python
number = [int(w) for w in input().split(" ")]
square = [ i*i for i in range(0, number[1]) if number [0] <= i*i <= number[1]]


print(len(square))
```

## 錯誤訊息

Wrong Answer

## 問題描述

找不到可以測出 Wrong Answer 的條件，不知道自己錯在哪

**Comment by alexypdu** [comment]
輸入 `0 1` 應該要輸出 `2`，另外你的寫法會 TLE 喔，請參考其他有關這題的 issue。
