### ISSUE TITLE
[Homework 3] 揪狼殺

### ISSUE THREAD

**Issue by numen1879** [coding-coworking-club/python-2019-fall#196]
## 程式碼

```python
# 請把程式碼填在這！
```

## 問題描述

1.想請問題目中說：「如果人數人數夠，則選擇人數至少十二人中，連續最長的時間（輸出起始時間）」，想確認一下這裡的連續最長時間是指至少12人中其中一人最長的時間，還是指這12個人都可以持續的最長時間呢?或是兩者都不是@@
2.呈上，本題的sample2的答案，實在想不出來為什麼是17點，因為本題已經有某些時間點是12人以上，所以應該要看的是最長連續時間，如果這個最長連續時間為超過12人的時間中，某一個最長的時間，那應該是14點(其中一人可以玩連續10小時)，但如果是12人都可以持續的最長時間，應該是18點(至少12人可以連續玩2小時)。

以上再請助教解答，謝謝。

**Comment by Kevinweisl** [comment]
1. 簡單來說因為希望可以玩久一點，所以希望每個時間點都至少有 12 個人
因此，就是看哪段時間是最長的就是
所以，不是其中一人最長的時間，也不是這12人都可以待的時間
例如： 12 點有 12 個人（包含小明），13 點也是 12 個人（但小明有事找了小華來幫他），那我們就會把這兩個時間點算是連續符合兩個小時。

2. 根據這個 sample 計算每個時間點有空的人數如下：
[11, 9, 9, 12, 7, 11, 12, 9, 9, 8, 8, 11, 9, 11, 14, 12, 10, 13, 16, 16, 13, 10, 10, 10]
我們可以知道從 17 點開始連續四個小時都有至少 12 個人
因此答案就是 17

**Comment by numen1879** [comment]
謝謝回覆，原來是對題目理解錯誤，已解決。
