### ISSUE TITLE
[Homework 3] 括號合法

### ISSUE THREAD

**Issue by 2019Chung** [coding-coworking-club/python-2019-fall#198]
## 提交連結

https://judge.ccclub.io/status/8329b73ce367fae7942da9af49a79063

## 程式碼

```python
# 請把程式碼填在這！
open_bracket = "("
close_bracket = ")"

content = input().replace(" ","")

check_bracket = []
for i in content:
    if i == open_bracket:
        check_bracket.append(i)
    elif i == close_bracket:
        if len(check_bracket) > 0:
            check_bracket.pop()
        elif len(check_bracket) == 0:
            check_bracket.append(i)
            break

if len(content) != 0:
    if len(check_bracket) == 0:
        print("True")
    else:
        print("False")
else:
    print("False")
```

## 錯誤訊息

Wrong answer!

## 問題描述

已測過Sample input，想請問助教需要修正的部分～

**Comment by Kevinweisl** [comment]
請敘述一下你目前的想法，方便助教幫助你釐清問題。

**Comment by 2019Chung** [comment]
當輸入的字串為"("，會進入check_bracket的list當中；而當輸入的字串為")"時，會刪除check_bracket中的一個"("。最後當check_bracket list中沒有任何括弧時，輸出True，否則輸出False

- 在判斷輸入為")"、要刪除"("前，會先確定check_bracket當中是不是還有"("。如果沒有，會在check_bracket插入一個")"，直接跳出迴圈，讓len(check_bracket) 等於1，輸出False。

- 判斷len(content) 目的是讓空字串輸出False。

**Comment by Kevinweisl** [comment]
你在空字串的部分想錯了喔！
你的做法中，空字串的狀況下 `len(content)` 一樣會是 1 喔

**Comment by 2019Chung** [comment]
想請問助教空字串的定義為何，因為程式碼修改過後還是Wrong answer，謝謝助教～
https://judge.ccclub.io/status/f080e32e9970f8dbe64db65639aa3e87

**Comment by alexypdu** [comment]
空字串就是要輸入 input 的時候直接按 `Enter`。目前你的程式會印出`False`：

**Comment by 2019Chung** [comment]
謝謝助教～
