### ISSUE TITLE
（範例）[General] 3-3：重複輸出

### ISSUE THREAD

**Issue by alexypdu** [coding-coworking-club/python-2019-fall#2]
## 提交連結

https://judge.ccclub.io/status/ff94eaeaae6175d084f1c4588c503274

## 程式碼

```python
s1 = input()
s2 = input()
print(s1 * int(s2))
print(s2 * int(s1)
```

## 錯誤訊息

![screenshot](https://user-images.githubusercontent.com/28721952/64923034-943eea80-d808-11e9-96c8-684d7fe230c9.PNG)

## 問題描述

好像哪裡怪怪 der 😕

**Comment by oscarcyhsu** [comment]
最後一行少括號

**Comment by alexypdu** [comment]
WOW 大神解惑 ><，太感謝了 😍
