### ISSUE TITLE
[General] 6-4：數字和

### ISSUE THREAD

**Issue by pilipala1006** [coding-coworking-club/python-2019-fall#20]
## 程式碼

```python
n=123
l=list(str(n))
num=0
total=0
for i in range(len(l)):
  total+=num
  num+=1
  print(total)
```

**Comment by pilipala1006** [comment]
不知道為什麼問題描述跑不出來，補在這：
先輸入一個整數，然後建立一個將此整數切割成字串並建立一個list，接下來在list的範圍內嘗試算出total但失敗qq

**Comment by alexypdu** [comment]
> 不知道為什麼問題描述跑不出來，補在這：
> 先輸入一個整數，然後建立一個將此整數切割成字串並建立一個list，接下來在list的範圍內嘗試算出total但失敗qq

因為你把他填在 `<!-- -->` 裡面，那是註解，主要是給你們發問的時候看的提醒事項 😀

**Comment by alexypdu** [comment]
是說這應該不是第三週的隨堂練習吧 XD，我幫你調整囉。

**Comment by hyusterr** [comment]
你的程式碼只能處理 n=123 的情況，記得測試資料不只 123 喔

**Comment by pilipala1006** [comment]
```python
n=int(input())
hun=n // 100
ten=(n-(hun*100))//10
one=n%10
list=[hun,ten,one]
total=0
n=0
for i in list:
  total+=i
  n+=1
print(total)
```

這樣子的話是編譯器跑的出來 但批改系統顯示wrong answer><

**Comment by alexypdu** [comment]
1. 你批改系統最近一次的提交最後一行的 `print` 有縮排
2. input 不保證是三位數

**Comment by alexypdu** [comment]
@pilipala1006 因為你超過三天沒有回覆，我們就先關掉這個 issue 囉，如果還有問題可以再 reopen！
