### ISSUE TITLE
[Homework 3] 揪狼殺

### ISSUE THREAD

**Issue by Carols92247** [coding-coworking-club/python-2019-fall#201]
## 提交連結

https://judge.ccclub.io/status/1692129941cccd9bc3f241dbbbad77b4

## 程式碼

```python
friendn=int(input())
alltime=[0]*24
abtw=[]
for i in range(friendn):
    avtime=input().split()
    for j in range(len(avtime)):
        t=int(avtime[j])
        alltime[t]+=1
if max(alltime)<12:
    ans=alltime.index(max(alltime))
    print(ans)
else:
    for k in range(len(alltime)):
        if alltime[k]>=12:
            abtw.append(k)
    countlst=[]
    count=0
    for l in range(len(abtw)-1):
        if int(abtw[l+1])-int(abtw[l])==1:
            count+=1
            countlst.append(count)
        else:
            count=0
            countlst.append(count)
    maxcount=countlst.index(max(countlst))
    maxnumber=maxcount-(max(countlst)-1)
    print(abtw[maxnumber])
```

## 錯誤訊息

Wrong Answer
## 問題描述

測試都有跑過，但不知為何是Wrong Answer

想法：
1.先建立一個有24小時的alltime list，裡面的值都是0，把大家有空的時間記錄進去
2.判斷alltime list中max有沒有小於12，若小於12則print出list中最大值的位置(也就是幾點)
3.若list中有大於12的，則將有大於12的時間放入abtw list中
4.接著創建 countlst list，用來記錄連續幾個小時(雖然只算到list數量減一，但不會因此而沒有算到最後一個時間點，因為是用L+1減去L來判別)
5.最後找出連續小時數最高的那個位置，但是由於最高的那個位置是連續的小時數，並不是開始的時間點，所以會再扣掉。舉例，若abtw(有超過12小時的時間)=[1,3,7,8,9,10,13]，則countlst=[0,0,1,2,3,0]，所以我找出最大值是3，但由於3是連續小時數，所以要找到應該是有最大值那串連續數字中的1的位置的時間
6.最後印出答案

**Comment by Kevinweisl** [comment]
先確認一下：
如果最高連續是 2 ，但有兩個狀況符合（比如說 9~10點，20~21點），你的程式會輸出什麼？
如果最高連續事 1 ，但有五個狀況符合（比如說：3、7、9、18、21 點），你的程式會輸出什麼？

**Comment by Carols92247** [comment]
跑過了～謝謝助教～
