### ISSUE TITLE
[Homework 3] 括號合法

### ISSUE THREAD

**Issue by kuanyinchen** [coding-coworking-club/python-2019-fall#206]
## 提交連結

https://judge.ccclub.io/status/189780c7c7e1e3a0f167d04e96486dea

## 程式碼

```python
symbol=input()
symbol_list=[]
for s in symbol:
    symbol_list.append(s)
if symbol_list.count('(') == symbol_list.count(')') and symbol_list[0] != ')':
    print("True")
elif len(symbol_list) == 0 :
    print("True")
else:
    print("False")
```

## 錯誤訊息

Wrong answer

## 問題描述

題目有強調測資可以是空字串，我看Github上有討論空字串為True，我理解的空字串測資是在input按空白鍵後Enter，在Jupyter上都是正確的，但過不了Judge系統ＱＱ

**Comment by alexypdu** [comment]
空字串是 input 時直接按 `Enter`。
