### ISSUE TITLE
[Homework 3] 括號合法

### ISSUE THREAD

**Issue by Thomas-Ke** [coding-coworking-club/python-2019-fall#208]
## 提交連結
https://judge.ccclub.io/status/5d0817cb71be87139a71ca92bab5b30d

## 程式碼

```python
# 請把程式碼填在這！
bracket=input()
num1=0
num2=0
for i in range(len(bracket)):
    if bracket[i]=="(":
        num1+=1
    if bracket[i]==")":
        num2+=1
    if num1<num2:
        print("False")
        break
if len(bracket)==0:
    print("True")
elif num1==num2 and (bracket[0]=="(" and bracket[-1]==")"):
    print("True")
```

## 問題描述
輸入括號，num1代表"("的個數，num2代表")"的個數，如果是空字串印出True；如果"("的數量等於")"的數量，
而且字串的最左邊是"("，且字串的最右邊是")"，印出"True；其他則印出"False"。
在jupyter notebook上都可以通過，但是judge顯示Wrong answer，不知道問題在哪裡QQ

**Comment by alexypdu** [comment]
試試看 `())(()`？

**Comment by Thomas-Ke** [comment]
上面是新的程式碼，())(()印出False，測資和空字串也都可以，但是還是Wrong answer，不知道還有什麼是沒辦法過的?

**Comment by alexypdu** [comment]
試試只有一個 `(`？
