### ISSUE TITLE
[General] 綜合1-2：一奇多偶

### ISSUE THREAD

**Issue by yihmnz** [coding-coworking-club/python-2019-fall#21]
## 提交連結
https://judge.ccclub.io/status/23df2a2c14fb163a96fd2b1299ba0e94

## 程式碼

```python
def judge(I):
    n = 1
    while n > 0:
        if I.count(str(n)) % 2 != 0:
            print(n)
            break
        else:
            n += 1

I = input().split(" ")
judge(I)
```

## 錯誤訊息
Time Limit Exceeded 

## 問題描述
題目：
給一個內含整數的串列 lst，其中只有一個元素出現過奇數次，其餘元素皆出現偶數次，找出出現奇數次的值並將其印出。
我的腦袋邏輯：
我使用迴圈以及list.count去計算
從n=1開始計算原本輸入的串列中含有幾個n.....
然後在計算到奇數時就print和break
但是不知道為什麼這個程式碼都跑1.99秒到2秒間
也不知道該怎麼去修正....
請幫我解惑QQ

**Comment by hyusterr** [comment]
用你這個方法的話，如果奇數個的數字剛好很大，那你的程式就會跑很~久，而且每個迴圈都要重新數依次串列裡的那個數字有幾個，所以才會TLE
例如：1 1 1000000000000 2 2 2 2 
可以再想想看其他方式喔

**Comment by alexypdu** [comment]
你的程式從 1 開始，檢查每個正整數在串列裡面出現的次數。如果：

1. 串列裡面有負數 => 檢查不到
2. 串列裡面的數字都很大 => 會浪費很多時間在檢查不在串列裡面的小數字

**Comment by yihmnz** [comment]
謝謝~
我後來用set去算
已解決~
