### ISSUE TITLE
[Homework 4] 字母接龍

### ISSUE THREAD

**Issue by emily41127** [coding-coworking-club/python-2019-fall#219]
## 程式碼

```python
# 請把程式碼填在這！
dic = {}
answer = []
for i in range(0 , 20):
    num = input().split()
    search = num[0]
    dic[search] = num[1]
    
a = input()
answer.append(a)
answer.append(dic[a])
b = dic[a]
while True:
    if b == a:
        answer.remove(answer[-1])
        print(answer)
        break
    else:
        answer.append(dic[b])
        b = dic[b]
```

## 問題描述

思路主要是
1.將輸入的字母和對應字母存成一個字典
2.透過KEY查找對應值
3.將對應值存入一個list中
4.如果相同就停止，並且print出列表
這邊跑出來都沒有問題，有問題示最後跑出來的格式，所以想請問最後output的格式是什麼?
因為最後出來的好像是str格式，也就是['s', 'd', 'a']這種樣子，但是如果要用for迴圈把 ' ' 和 , 拿掉的話，系統又會跑出int不能遍歷的提示(可是他的格式不是str嗎??QAQ)
如果要把列表裡面增加的東西變成int，又會因為輸入的東西不是數字而發生錯誤
想請助教開示此題怎解QAQ

**Comment by Kevinweisl** [comment]
想確認一下，你的 `answer` 這個變數是一個 list，然後裡面都是字串對吧？
試試看我們曾經在課堂上補充的 str.join 呢？

**Comment by emily41127** [comment]
我成功了!!!謝謝:)))
