### ISSUE TITLE
[General] 5-1：翻箱倒櫃 

### ISSUE THREAD

**Issue by Tkkjie** [coding-coworking-club/python-2019-fall#23]
## 程式碼

```python
a=input()
b=input()
s=input()

lst1= a.split()
lst2= b.split()

print( s in lst1 or lst2)
```

## 問題描述

在jupyter上測試都沒問題，但批改系統不給過，不知道問題出在哪？
感覺很簡單的題目花了好長時間QQ

**Comment by hyusterr** [comment]
你現在打的最後一行，在 python 看來是：
( s 在 lst1 裡 ) 或 lst2
前面是一個要判斷真偽的變數 後面是 一個串列
但這樣應該不是你想要的效果喔

**Comment by Tkkjie** [comment]
感謝協助！

剛剛試著將最後一行改為 ：
print( (s in lst1) or (s in lst2))  就通過了。

想追問一個問題，為什麼不能寫成 print(s(lst1 or lst 2))?
這個和 print( (s in lst1) or (s in lst2)) 的差異在哪裡呢？

**Comment by alexypdu** [comment]
```python
(s in lst1) or (s in lst2) # <--- 如果 s 在 lst1 裡面或 s 在 lst2 裡面則為真，否則為假

s in (lst1 or lst2) # <--- 如果 s 在 (lst1 or lst2) 裡面則為真，否則為假
```

`lst1 or lst2` 兩個串列取 `or`，若 `lst1` 非空則結果為 `lst1`，反之為 `lst2`

範例：

```python
[1] or [] # [1]
[1] or [2] # [1]
[] or [3] # [3]
[] or [] # []
```

詳情參閱：https://docs.python.org/3/library/stdtypes.html#boolean-operations-and-or-not

**Comment by Tkkjie** [comment]
搞懂了，謝謝～
