### ISSUE TITLE
[Homework 4] 字母拼圖

### ISSUE THREAD

**Issue by wenwen-17** [coding-coworking-club/python-2019-fall#239]
## 提交連結
https://judge.ccclub.io/status/ffe10cf6d3c07b31cfbb45e6b0050d55

## 程式碼

```python
def char_puzzle(lst):
    letter='abcdefghijklmnopqrstuvwxyz'
    cal=[]
    for kk in range(len(lst)):
        for word in range(len(letter)):
            for ii in range(len(lst[kk])):
                if letter[word]==lst[kk][ii]:
                    cal.append(letter[word])
    cal=sorted(cal)
    ans=[cal[0]]
    for word in range(1,len(cal)):
        if cal[word]==cal[word-1]:
            continue
        else:
            ans.append(cal[word])
    ans=sorted(ans)
    return ans
    
lst=input().split(',')
print("".join(char_puzzle(lst)))
```

## 錯誤訊息
Wrong Answer

## 問題描述

*問題:在jupyter notebook上有通過但批改系統顯示錯誤，原本以為是輸入格式的問題，後來發現好像沒差，一直不知道哪錯(TAT)
*思路:將lst中的字串先分割出來，然後逐一將各個字串裡的字母挑出後排列，然後放到同一個list裡(也就是cal)。然後將cal進行排列後刪除重複的字母，最後再排列一次並回傳。

**Comment by Peterorr** [comment]
提供兩個想法：
迴圈部分用了三圈可能會 time limit exceed，是否有其必要？
另外，是否需要全部的字母都放進串列後->排序->刪除相同的部分？
是否有其他判斷方式呢？

**Comment by oscarcyhsu** [comment]
1. 請實作函式回傳結果字串(不是list) 並且不需要print()
2. 請參考 @Peterorr 關於TLE的想法，試試看有沒有更好的方法

**Comment by wenwen-17** [comment]
好的!謝謝
