### ISSUE TITLE
[Homework 5] 數字交換最大值

### ISSUE THREAD

**Issue by wenwen-17** [coding-coworking-club/python-2019-fall#241]
## 提交連結
https://judge.ccclub.io/status/40a629d3f180e7f06cd17e902b2fde7b

## 程式碼

```python
num=int(input())
num=str(num)
ans=[]
for i in range(len(num)):
    ans.append(num[i])
max_index=num.index(max(num))
max_index=int(max_index)
ans[0],ans[max_index]=ans[max_index],ans[0]
number="".join(ans)
print(int(number))
```

## 錯誤訊息
Wrong Answer

## 問題描述

*問題:試了很多測資，在jupyter notebook上都沒有問題，但批改系統一直不通過，不確定是不是自己遺漏了甚麼
*個人思路:將數字轉換成字串後，一個一個放入串列中，找出最大的數字和第一位交換，然後將字串轉成一個整數後輸出

**Comment by Kevinweisl** [comment]
你試試 `99999788888` ，正確答案應該是 `99999888887`
