### ISSUE TITLE
[Homework 1] 字元強調

### ISSUE THREAD

**Issue by b05505003** [coding-coworking-club/python-2019-fall#26]
## 提交連結
https://judge.ccclub.io/status/387dd1d77aec1c8712c3e3edfab38417

## 程式碼

```python
# 請把程式碼填在這！
w=input();
sentence=input().split(" ");
for i in range(len(sentence)):
    if (sentence[i][0] == w):
        b=sentence[i].replace(sentence[i][0], w.upper());
        if (i==len(sentence)-1):
            print(b,end="");
        else:
            print(b,end=" ");
    else:
        if (i==len(sentence)-1):
            print(sentence[i],end="");
        else:
            print(sentence[i],end=" ");
            
```

## 問題描述

1. 輸入子母
2. 輸入句子並切割句子變成list
3. 檢查list中每個元素的第一個字母
4. 若元素的第一個字母為1.的輸入字母且不為list中最後一個元素：
=> 將第一個字母大寫之後，加空格輸出
5. 若元素的第一個字母為1.的輸入字母且為list中最後一個元素：
=> 將第一個字母大寫之後，不加空格輸出
6. 若元素的第一個字母不為1.的輸入字母且不為list中最後一個元素：
=> 將元素加空格輸出
7. 若元素的第一個字母不為1.的輸入字母且為list中最後一個元素：
=> 將元素輸出

我利用sample input檢查答案跟sample output是一樣的，可是submit是wrong answer。想請問我是不是還有考慮不夠周到的地方

**Comment by sc090410** [comment]
string.replace()會將字串裡面的所有舊字元換成新字元～舉例來說，determined這個字如果要強調的是d，就會變成DetermineD，詳見[replace的用法](http://www.runoob.com/python/att-string-replace.html)

**Comment by alexypdu** [comment]
@linyutingting 我看你批改系統有過關了，下次麻煩在這邊留言一下讓我們知道你的問題解決了，我們才方便 close issue 唷 🚀
