### ISSUE TITLE
[Homework 1] 字元強調

### ISSUE THREAD

**Issue by emily41127** [coding-coworking-club/python-2019-fall#28]
## 提交連結

https://judge.ccclub.io/status/b18155d263ba9ac7cff0dbdac8eb0ac9

## 程式碼

```python
# 請把程式碼填在這！
key_word=input()
sentence=input().split(" ")
key_word_upper=key_word.upper()
for i in range(len(sentence)):
    if (sentence[i][0]==key_word):
        print(sentence[i].replace(key_word, key_word_upper),end=" ")
    else:
        print(sentence[i],end=" ")
```

## 問題描述

在jupyter notebook上測試可以，但是放到judge系統上就變成wrong answer.
後來有發現是因為句尾會多一個空格，可是不知道要怎樣才能只拿掉句尾的空格QQ

我的思路如下:
先輸入一個key_word
再輸入一個sentence並切割成一個list
key_word_upper定義為key_word大寫
下面開始跑sentence list的迴圈
    如果sentence第一個變數i等於key_word，則輸出大寫的key_word並空一格
    否則直接輸出sentence，並空一格

**Comment by oscarcyhsu** [comment]
因為replace會把除了字首的字母也換成大寫喔

**Comment by emily41127** [comment]
y
So don't you worry your pretty little mind, People throw rocks at things that shine.
So don't You worry Your pretty little mind, People throw rocks at things that shine. 
可是我前面有設定要第一個字母才會變成大寫，上面是這個程式用jupyter notebook跑出來的結果，和judge系統上的結果一樣QQ
但是放到judge系統上顯示出來的是wrong answer.

**Comment by sc090410** [comment]
因為你的條件是詞的字首是該字的時候才會replace，但是你測的測資並沒有這種情況（像是要強調的是d，遇到的字是determined）你可以用這個測看看，應該會變成DetermineD而不是Determined

**Comment by emily41127** [comment]
喔喔喔好，我知道問題在哪裡了，謝謝XDDD
