### ISSUE TITLE
[Homework 1] 字元強調

### ISSUE THREAD

**Issue by yhchang1** [coding-coworking-club/python-2019-fall#31]
## 提交連結

https://judge.ccclub.io/status/3d236d8418a8fe0f16616c16117e8aa3

## 程式碼

```python
# 請把程式碼填在這！
```

## 問題描述

我的想法是
1. 輸入字母
2. 輸入句子
3. 把句子切割
4. 在迴圈內如果切割出來的字字首等於1輸入的字母--->字首換成大寫
5. 把list接回去變成字串

在jupyter上測試兩個題目給的例子都沒問題，但是交出去是錯的，想知道我哪裡沒想清楚或打錯~謝謝!!

**Comment by alexypdu** [comment]
Duplicate of #26 and #28
