### ISSUE TITLE
[General] 6-3：母音種類個數

### ISSUE THREAD

**Issue by hiyutzu** [coding-coworking-club/python-2019-fall#34]
## 程式碼

```python
# 請把程式碼填在這！
def vowel_count(s):
       for item in s :
             if item in vowels:  #判斷item是否在vowels串列中
                   item_counts = 1 + item_counts
       print(item_counts)

vowels = ["a", "e", "i", "o", "u"]
s = input()
item_counts = int()

```

## 錯誤訊息

local variable 'item_counts' referenced before assignment

## 問題描述

在Juptyer notebook可跑出結果，但影片的作業批改系統出現上述錯錯

**Comment by alexypdu** [comment]
> local variable 'item_counts' referenced before assignment

你的第四行

```python
item_counts = 1 + item_counts
```

`item_counts` 在前幾行還沒有被定義過，所以 `=` 右邊要 `1 + item_counts` 的時候就出錯了。

在 Jupyter Notebook 裡面所有格子（cell）是共用變數的，所以可能你執行格子的上面幾格有定義過。在 judge 上每次執行都是重新來過的，這個差異要注意一下。
