### ISSUE TITLE
[General] 5-1：翻箱倒櫃

### ISSUE THREAD

**Issue by Thomas-Ke** [coding-coworking-club/python-2019-fall#35]
## 提交連結
https://judge.ccclub.io/status/7245f9e903c4d344ad3497b870d387b1

## 程式碼

```python
a=list(input())
b=list(input())
c=str(input())
if (c in a) and (c in b):
    print("True")
else:
    print("False")
```

## 問題描述
if的部分是指：如果ｃ在ａ和ｂ裡面就印＂Ｔｒｕｅ＂，其他都是＂Ｆａｌｓｅ＂
在jupyter notebook上都可以通過，但批改系統就不行，不知道哪邊有問題QQ

**Comment by alexypdu** [comment]
題目本身的兩個範例測資並沒有通過唷！

**Comment by Thomas-Ke** [comment]
沒事了，看錯題目XD
