### ISSUE TITLE
[General] 4-4：直角三角形

### ISSUE THREAD

**Issue by goodluck77** [coding-coworking-club/python-2019-fall#40]
## 程式碼

```python
a=int(input())
b=int(input())
c=int(input())

if (a**2 + b**2 = c**2) or (a**2+c**2=b**2) or (b**2+c**2=a**2):
    print("True")
else:
    print("False")
```

## 錯誤訊息

File "<ipython-input-10-e23104ebbf48>", line 5
    if (a+b=c ) or(a+c=b) or (b+c=a):
           ^
SyntaxError: invalid syntax

## 問題描述

想利用直角三角形兩個短邊平方的合=長邊的平方 來解題，但是無法成功，也不了解程式碼哪裡有問題，勞煩各位大大解惑~感謝!!
p.s不知道為什麼 ** 會不見，但我有打

**Comment by alexypdu** [comment]
為什麼要把我預填的內文給刪掉 😭 
````
```python
# 請把程式碼填在這！
```
````

**Comment by sc090410** [comment]
呀…記得把程式碼寫在code的區塊裡面！
ˋˋˋ python
這邊！
ˋˋˋ

**Comment by alexypdu** [comment]
> p.s不知道為什麼 ** 會不見，但我有打

因為 Markdown 語法的關係，原本被夾在 ** 中間的文字會變成粗體，把 code 填在我幫你預留的位子就不會出錯了，先幫你改囉 😀

**Comment by alexypdu** [comment]
看起來你給的程式碼跟你提供的錯誤訊息中出錯的地方匹配不起來，麻煩你確認一下唷！

**Comment by hungminchen** [comment]
在想如果要判斷相等的話是不是應該要用兩個等號( == ), 而不是用一個等號阿~
