### ISSUE TITLE
[General] 8-2：最長字串

### ISSUE THREAD

**Issue by waynepenguin** [coding-coworking-club/python-2019-fall#42]
## 程式碼

```python
#HW 8-2
def max_len(s):
    s = s.split()
    lens = s[0]
    for i in range(len(s)):
        if i>0:
            if len(s[i])>len(s[i-1]):
                lens = s[i]
    return lens

a = input()
print(max_len(a))
```

## 問題描述

這題的批改系統貌似有問題
if len(s[i])>len(len(s[i-1])):
我這樣寫他給我"accept"

這裡應該要比較的是len(lens)
如果跑的是
fg gggggg ght hhyh
就會有問題

**Comment by sc090410** [comment]
嗨，我看好像你寫跟len(lens)比較的code也已經accepted了，如果沒有問題我就close issue囉？
至於`if len(s[i])>len(len(s[i-1])):`會過應該也只是測資的巧合～
