### ISSUE TITLE
[General] 綜合1-4：括號合法

### ISSUE THREAD

**Issue by yihmnz** [coding-coworking-club/python-2019-fall#43]
## 提交連結
https://judge.ccclub.io/status/de7501eb3d115e3fd793333d7dd71625

## 程式碼

```python
I = input()
mark = []
for i in range(len(I)):
    if I[i] == "(":
        mark.append(1)
    elif I[i] == ")":
        mark.append(-1)
        
judge = 0

if mark.count(1) == mark.count(-1):
    for x in range(len(mark)):
        judge += mark[x]
        if judge < 0:
            print("False")
            break
        elif x == (len(mark)-1):
            print("True")
else:
    print("False")
```

## 錯誤訊息
wrong answer

## 問題描述
問題：
輸入一個字串 s，如果括號組合合法（每一個左括號都對應一個右括號且位置正確），則輸出 True，否則，輸出 False。
我的思路邏輯：
把左括號設為1右括號設為-1，創造一個新的List
如果是["(", "(" ,")" ,")"]就是[1,1,-1,-1]的概念
然後去進行推論
首先設一個IF 作為判定所有左括號與所有右括號的數量是否一致
如果確定數量一致便進行判定左右是否都能夠刮起來
以judge為0 如果遇到jugde<0的情況 
表示按照順序的右括號多於左括號了 無法配對
ex. ()) --> 1-1-1 <0
便輸出False
然而用elif 判定到最後一個數 x = len(mark)-1時
直接輸出True 表示沒問題(數量相同且配對的很好)
在Jupyter上計算時一樣沒什麼問題
但是是wrong answer
請大神幫我找出解題的盲點
謝謝!

**Comment by sc090410** [comment]
嗨！如果沒有任何括號（就是輸入為空字串）的情況下，應該也要判斷為True喔～（因為沒有不合法的括號！）

**Comment by cyhsieh264** [comment]
> 嗨！如果沒有任何括號（就是輸入為空字串）的情況下，應該也要判斷為True喔～（因為沒有不合法的括號！）

原來是這個意思！一直以為是，只要s當中沒有“合法的括號組合”，就輸出為False......
