### ISSUE TITLE
[Homework 1] 字元數數

### ISSUE THREAD

**Issue by annie890114** [coding-coworking-club/python-2019-fall#44]
## 提交連結
https://judge.ccclub.io/status/ddf3d9e35bcbcbea462203467c4a8193

## 程式碼
```python
word=input()
sen=input()

word1=word.split()
x=word1[0]
y=word1[1]
z=word1[2]

a=sen.count(x)
b=sen.count(y)
c=sen.count(z)
print(a,b,c)
```

## 問題描述
請問為什麼我用python shell 是顯示可以成功?但批改系統顯示錯誤?是哪裡我漏掉了嗎?謝謝

**Comment by sc090410** [comment]
嗨嗨～我看了一下你答對的測資狀況，看起來是範例測資也還沒有過！不妨看一下跑範例測資的結果，搭配Trace code的工具來檢查一下哪裡出了問題吧～

**Comment by alexypdu** [comment]
提交前請預覽。
