### ISSUE TITLE
[General] 8-3：及格門檻

### ISSUE THREAD

**Issue by yhchang1** [coding-coworking-club/python-2019-fall#46]
## 提交連結

https://judge.ccclub.io/status/6a3814bac703dbc5f16b69d73c70cc33

## 程式碼

```python
def threshold(a, b, arr=[]):
    a = a.split(" ")
    
    
    for i in range(len(a)):
        arr.append(a[i]>=b)
       
    return arr
            
a = input()
b = input()
print(threshold(a, b))
```

## 錯誤訊息

wrong answer

## 問題描述

測了sample和幾個例子都沒問題，想請問是哪裡錯了~~謝謝!!

**Comment by hyusterr** [comment]
你的函數裡面的串列裡的數字的資料型態不是數字喔~
在 python 裡面字串也是可以比大小的，但是比的方法不太一樣，會是比字串的每個位置的ASCII值大小，所以 '55' 會大於 '111' ，但這裏我們要比的是數值的大小喔

你可以試試看這筆測資：
111 22 33 44 55 66
55

**Comment by alexypdu** [comment]
兩個字串在比大小的時候，會從頭開始，先比較雙方第一個字元，看誰的 ASCII 值大，如果相同就比下一個，以此類推。如果分不出勝負，則長度較短的字串判定較小。

```python
>>> "a" < "zzz"
True
>>> "aaa" < "z"
True
>>> "b" < "a"
False
>>> "abc" < "abcd"
True
>>> "abcd" < "abce"
True
>>> "A" < "a"
True
>>> ord("A")
65
>>> ord("a")
97
```

**Comment by hyusterr** [comment]
感謝允平補充

**Comment by yhchang1** [comment]
了解~謝謝兩位！ 現在ok了~~~
