### ISSUE TITLE
[Week 3] 檢查日期

### ISSUE THREAD

**Issue by wenzhichua** [coding-coworking-club/python-2019-fall#47]
## 程式碼

```python
# 請把程式碼填在這！

if month==1 or 3 or 5 or 7 or 8 or 10 or 12:
   do something
```
## 問題描述

想問一個基本的問題，如果想要在month的數值為‘大月’的數值的時候，再做某些處理，想寫一個if month=1,3,5,7,8,10,12，有什麼更簡便的方法嗎?
 if month==1 or month==3 or month==5.........這樣的寫法應該可以但是太冗長了> <
像我在上面提交的程式碼是不行的嗎 QQ
感謝回答～

**Comment by alexypdu** [comment]
提交前請預覽。

**Comment by wenzhichua** [comment]
改好了～～

**Comment by alexypdu** [comment]
我會利用串列及其 index 來存每個月份對應的天數 👀

**Comment by wenzhichua** [comment]
好！我試試看！

**Comment by wenzhichua** [comment]
想再請問一個：請問輸出結果的方式是 “輸入1個日期，回覆1次” 還是“ 輸入end之後，才顯示所有的結果”呢？

**Comment by sc090410** [comment]
都可以～我們比對輸出結果的方式是看最後的輸出結果！所以兩種都可以
