### ISSUE TITLE
[Homework 1] 字元強調

### ISSUE THREAD

**Issue by 2019Chung** [coding-coworking-club/python-2019-fall#48]
## 提交連結

https://judge.ccclub.io/status/b4cbac9ee318143db457bac44e315497

## 程式碼

```python
# 請把程式碼填在這！
chr = input()
str = input()
str_sep = str.split() 

cnt = 0
for i in str_sep:
    if cnt:
      print("", end = " ")
    if i[0] == chr:
        i = i.replace(i[0],chr.upper())
    print(i, end="")
    cnt = cnt + 1
```

## 錯誤訊息

Wrong answer!

## 問題描述

在Jupyter測試成功，批改系統失敗。

**Comment by hyusterr** [comment]
在程式邏輯之外，有幾點你可以先注意：
1. str 跟 chr 都是 python 的內建函式，盡量不要用他們來當變數名稱
2. 第一個 if 底下的縮排

程式邏輯方面，注意 replace 是將整個字串裡的所有這個字元都換掉，而題目只要求改第一個字元，你可以試試看這筆測資：
t
taiwan tilts titans

**Comment by 2019Chung** [comment]
瞭解，非常感謝，已經更正完畢了～
