### ISSUE TITLE
[Homework 1] 數字相加

### ISSUE THREAD

**Issue by winnywu508** [coding-coworking-club/python-2019-fall#5]
## 提交連結

https://judge.ccclub.io/status/31baf4075cccfb743dde9dbaea3fb0ee

## 程式碼

```python
a = input()
a = a.split(" ")

a_sum = [sum(map(int, s.split())) for s in a]     
sum(a_sum)
```

## 問題描述

請問這個code哪裡有問題啊 
jupyter notebook跑兩個input都出現對的output
但批改系統說是wrong answer :(

**Comment by hyusterr** [comment]
記得輸出結果喔~

**Comment by hyusterr** [comment]
還有記得下次貼 code 貼在 ``` ``` 裡面喔~

**Comment by alexypdu** [comment]
發文前請先 preview 確認，原先模板內預填的內容請不要刪除。

**Comment by winnywu508** [comment]
成功了！謝謝

好的我下次會注意：）
