### ISSUE TITLE
[General] 6-3：母音種類個數

### ISSUE THREAD

**Issue by eefish** [coding-coworking-club/python-2019-fall#50]
## 程式碼

```python
a = input()
vowels = ["a", "A", "e", "E", "i", "I", "o", "O", "u","U"]
items = 0
for j in vowels:
    for i in a:
        if j in i:
            items +=1

        else:
            items = items

print(items)
```

## 問題描述

 依題目意思同樣大寫或小寫的母音只能計數一次，但上面的程式碼還是會重覆算。不知如何解~

**Comment by sc090410** [comment]
在 `for i in a` 的這個迴圈裡面，你做的事情是把字串裡的每一個字元拿出來看，然後去看 `if j in i` 的話計數就加一，不過這樣整個程式碼的邏輯就會變成：
1. 檢查大小寫的每一個母音
2. 將字串拿出來逐一檢查是否等於這次拿出來的母音，是的話就 +=1
如此一來就會變成計算每一個母音出現的次數，而不是看每一種有沒有出現～

或許可以想一下：如果我已經要逐一檢查每個母音了，我應該要怎麼檢查他在不在字串裡面？有需要每個字元都看嗎？或是如果真的要每個字元都看，是不是有其他得到結果的方法呢？
