### ISSUE TITLE
[Week 3] 小明採蘋果

### ISSUE THREAD

**Issue by alemapnil** [coding-coworking-club/python-2019-fall#51]
## 程式碼

```python
s=input()
s=s.split(',') 
s=''.join(s) # s is 12345  是那一排蘋果樹
l=len(s)

if l==1 or l==2:
    print(0)

else:
    sum=[]
    for i in range(1,l-1):  # i是 左右都有蘋果樹的位置
        sum.append(int(s[i-1])+int(s[i])+int(s[i+1]))

    for j in range(1,l): #j是每棵蘋果樹的位置int
        if max(sum)==int(s[j-1])+int(s[j])+int(s[j+1]):
            if int(s[j-1])+int(s[j])==int(s[j-1])+int(s[j])+int(s[j+1]):
                print(j-1)
                break
            print(j)
            break
```

## 問題描述
我自己跑程式答案都正確，為何批改系統不接受??
我的思路是，先標出左右兩邊都有蘋果的樹，再將左樹、中樹、右樹的蘋果數量相加，個別相加的數字丟到列表中，該列表表示所有情況的蘋果數量總和。再將列表轉成集合，該集合便不會有重複出現的數字。再從集合裡抓出最大值，尋找哪個組合(左樹+中樹+右樹)與最大值相等，再取出中樹的位置。若有重複採收的數量相等之情況，我增加if情況取位置編號較小者。

**Comment by hyusterr** [comment]
想想看只有一棵樹或是兩棵樹的時候，你的程式會跑出什麼結果。
例如：
1
或
1,2

**Comment by alemapnil** [comment]
為什麼多設定一棵、兩棵樹了，但還是不行??
----------------------------------------------------------
s=input()
s=s.split(',') 
s=''.join(s) # s is 12345  是那一排蘋果樹
l=len(s)

if l==1 or l==2:
    print(0)

else:
    sum=[]
    for i in range(1,l-1):  # i是 左右都有蘋果樹的位置
        sum.append(int(s[i-1])+int(s[i])+int(s[i+1]))

    for j in range(1,l): #j是每棵蘋果樹的位置int
        if max(sum)==int(s[j-1])+int(s[j])+int(s[j+1]):
            if int(s[j-1])+int(s[j])==int(s[j-1])+int(s[j])+int(s[j+1]):
                print(j-1)
                break
            print(j)
            break

**Comment by alemapnil** [comment]
為什麼我多設定一棵、兩棵樹了，還是不行??


s=input()
s=s.split(',') 
s=''.join(s) # s is 12345  是那一排蘋果樹
l=len(s)
if l==1 or l==2:
    print(0)
else:
    sum=[]
    for i in range(1,l-1):  # i是 左右都有蘋果樹的位置
        sum.append(int(s[i-1])+int(s[i])+int(s[i+1]))
    for j in range(1,l): #j是每棵蘋果樹的位置int
        if max(sum)==int(s[j-1])+int(s[j])+int(s[j+1]):
            if int(s[j-1])+int(s[j])==int(s[j-1])+int(s[j])+int(s[j+1]):
                print(j-1)
                break
            print(j)
            break

**Comment by alemapnil** [comment]
我程式碼已經多設定了一兩棵樹的情況，但為何還是不行??
程式碼如我上面所調整的那樣，為何不行呢？

**Comment by sc090410** [comment]
嗨～建議下次附一下批改系統連結，然後請試試看 `5,7,0,4,1,2,10` 這筆測資吧，答案應該要是 5 才對喔

**Comment by alemapnil** [comment]
我改了，但還是不行，到底為何??

https://judge.ccclub.io/status/bed8b04ae7c8334cc1ac2c940fe58440

**Comment by alemapnil** [comment]
我改好了，為何還是不行??
https://judge.ccclub.io/status/7a42893c0b130a3a042f5a1636ddecb9

**Comment by sc090410** [comment]
嗨剛才有一點bug我們已經處理好了，也幫你按了Rejudge，已經Accepted了～
