### ISSUE TITLE
[Week 3] 中位數

### ISSUE THREAD

**Issue by cyhsieh264** [coding-coworking-club/python-2019-fall#53]
## 提交連結

https://judge.ccclub.io/status/32110ffff9247602f61a47f539ceab0b

## 程式碼

```python
lst = input().split()

if len(lst)%2!=0:
    print(float(lst[len(lst)//2]))
    
if len(lst)%2==0:
    print((float(lst[len(lst)/2])+float(lst[(len(lst)/2)-1]))/2)
```

## 錯誤訊息

TypeError                                 Traceback (most recent call last)
<ipython-input-4-33274dbdc248> in <module>
      5 
      6 if len(lst)%2==0:
----> 7     print((float(lst[len(lst)/2])+float(lst[(len(lst)/2)-1]))/2)

TypeError: list indices must be integers or slices, not float
## 問題描述

其實這題我在把程式碼最後一行的“/”改成“//”以後，已經在批改系統提交成功。

但還是有點疑惑，所以來提問：

上面程式碼欄位貼的是我原來寫的錯誤程式碼，在Jupyter Notebook上跑的時候，顯示最後一行出現TypeError的訊息（如上所附）。

可是在if len(lst)%2==0的條件下，不是已經保證len(lst)可以被2整除了嗎，為什麼系統還是會出現TypeError的訊息呢？

**Comment by sc090410** [comment]
這邊的TypeError說的是我們在用index取list裡的東西時，只能用整數來取，但是只要使用了 `\`出來的數字就會預設是 `float` 型態，所以他說出錯的那行才會有 TypeError～

**Comment by cyhsieh264** [comment]
原來是會預設float型態（恍然大悟），感謝！
