### ISSUE TITLE
[General] 7-2：加減長方形

### ISSUE THREAD

**Issue by lss19920912** [coding-coworking-club/python-2019-fall#54]
## 提交連結

https://judge.ccclub.io/status/20d39a289d276b1e410c1b9576b07b57

## 程式碼

```python
s = int(input())
y =  int(input())
for i in range(1, y +1) :
    for j in range(1, s + 1) :
        if (i % 2 != 0 and j % 2 != 0) or (i % 2 == 0 and j % 2 == 0) :
            print("+", end="")
        else :
            print("-", end="")     
    print("")
```

## 問題描述

juypter跑出來是對的，但是上傳作業系統一直說是wrong answer

**Comment by alexypdu** [comment]
請修改標題及內文格式。

**Comment by lss19920912** [comment]
抱歉我有縮排，但是不知道為什麼傳上來就沒有了

**Comment by alexypdu** [comment]
因為你把我預填的內文給刪掉了
````
```python
# 請把程式碼填在這！
```
````

**Comment by lss19920912** [comment]
> 因為你把我預填的內文給刪掉了
> 
> ```
> ```python
> # 請把程式碼填在這！
> ```
> ```

不好意思，我修改好了

**Comment by sc090410** [comment]
嗨嗨！我簡單的看了一下，請注意這題在Judge上面跟在Udemy上面的題意是不太一樣的哦～

**Comment by lss19920912** [comment]
> 嗨嗨！我簡單的看了一下，請注意這題在Judge上面跟在Udemy上面的題意是不太一樣的哦～

助教不好意思，我還是無法找到問題，請問您說題意不一樣是什麼意思呢

**Comment by alexypdu** [comment]
你範例測資二沒有過唷。
