### ISSUE TITLE
[General] 7-1：長方形

### ISSUE THREAD

**Issue by pilipala1006** [coding-coworking-club/python-2019-fall#56]
## 程式碼

```python
height = int(2)
width = int(3)
while height > 0:
    tmp = width
    while tmp > 0:
        print("*", end="")
        tmp -= 1
    print()
    height -= 1
```

## 錯誤訊息

Runtime Error

## 問題描述

在編譯器裡面有跑出來，但不知道為什麼批改系統顯示runtime error><

**Comment by Peterorr** [comment]
1. runtime error 的可能原因是 語法錯誤 ( syntax errors ) 
   可以搜尋一下是這是什麼意思。
2. 我們寫出來的程式要是「通解」，也就是不管長寬給訂多少，都要照題目敘述產生答案

**Comment by sc090410** [comment]
補充一下：
所謂的RuntimeError是指程式在運行當中出現錯誤，跟編譯錯誤（CompileError）不一樣。
會產生RuntimeError的可能有很多種，絕大多數是程式在運行中產生了錯誤，像是取用了不在範圍內的index、或是實際運行時發現型態不如我們所想所以無法進行我們想做的計算等等，但是是在沒有因為syntax語法出現無法compile的錯誤的前提之下。
