### ISSUE TITLE
[General] 8-1：乘積最大值

### ISSUE THREAD

**Issue by rose020** [coding-coworking-club/python-2019-fall#58]
## 程式碼

```python
l=input().split()
for i in range(len(l)-1):
    m=int(l[i]) * int(l[i+1])
    print(max(m))
```

## 錯誤訊息
'int' object is not iterable

## 問題描述
不知道這樣程式為什麼會跑不動，請問應該要做什麼更正？

**Comment by sc090410** [comment]
因為m是一個整數，而max是吃一個list當作參數，因為他要去「遍歷」這個list來找最大值，但是整數是一個不能遍歷的資料型態，所以才會出錯～

**Comment by rose020** [comment]
所以為什麼也辦法直接用list()轉換呢？

**Comment by rose020** [comment]
沒問題了～我自己解決了！謝謝
