### ISSUE TITLE
[Week 3] 記帳本

### ISSUE THREAD

**Issue by alemapnil** [coding-coworking-club/python-2019-fall#59]
## 程式碼

```python
s=input()
s=s.split(' ')
s=[int(i) for i in s] # s is list containing int.
si=[i for i in range(len(s))] # si 數列是位置表

while True:
    enter=input()
    enter=enter.split(' ') #enter is ['a','4'] enter[0]& enter[1]
    c=enter[0]
    n=int(enter[1])
    if c=='a':
        s.append(n)
    elif c=='r':
        if n in s:
            s.remove(n)
        else:
            pass
    elif c=='p':
        if n<0:
            s.pop()
        elif n>=0:
            if n not in si:
                pass
            else:
                s.pop(n)
    elif c=='q':
        if n in si:
            print(s[n])
            print(int(sum(s)/len(s)))
        else:
            print('Error')
        break
```

## 問題描述
我依照題目要求，把條件都列了上去，答案算出來都對，為何系統就是不接受??

**Comment by sc090410** [comment]
嗨！你最後在 `q` 的時候，做的檢查是檢查 `si`，但是你的list `s` 在更新的時候並沒有同時更新 `si`，所以如果後來list長度變長的話，就很有可能在明明有該index的情況底下輸出 `'error'`

**Comment by alemapnil** [comment]
我改了你所說的部份，但還是不行> <"

https://judge.ccclub.io/status/fa5d0ffd5723ea4c99cc0baf32be5a8b

**Comment by alexypdu** [comment]
@sc090410 please help take care of this issue 😄

**Comment by sc090410** [comment]
抱歉我現在才看到，一樣是 `a//b` 與 `int(a/b)` 的計算方式不同所導致的差異，在本題當中改成使用前者應該就沒問題了

**Comment by alemapnil** [comment]
一、可否解釋一下為何要用 a//b，而不是int(a/b) ?  我不太懂這兩個哪裡不一樣? 題目說無條件捨去至整數，a=int(-8.9999)，印出a是 -8，也是無條件捨去至整數，為何int(a/b) 不行?

二、另外我依照你說的將平均數改成a//b，但系統還是不能接受。
https://judge.ccclub.io/problem/180204

**Comment by alexypdu** [comment]
1. 
```python
>>> int(9 / 4)
2
>>> 9 // 4
2
>>> int(-9 / 4)
-2
>>> -9 // 4
-3
```

2.
```python
elif c=='q':
        if n in si: # <--- 你的 si 是一開始創造的，可是經過中間諸多指令後可能已經不符合現況了
            print(s[n])
            print(int(sum(s)/len(s)))
        else:
            print('Error')
        break
```

**Comment by alemapnil** [comment]
謝天謝地終於算出來了
https://judge.ccclub.io/status/aa0abb1b0e07e6017661d098cf8be138

但我還是不懂，為何無條件捨去至整數，是用a//b，即便a是負數也應該用int來算，為何用// ? 我查負數的無條件取整，是先用絕對值取整數後，再掛上"-"，而a//b是往下取整數，若負數的話就算進位了，並非無條件捨去，所以我完全不明白為何是a//b????  很是困擾，不知助教可否直接解釋?? 拜託了，感恩~ @alexypdu  @sc090410 @yang611 @hyusterr @Kevinweisl

**Comment by oscarcyhsu** [comment]
如果你有問題的是兩者結果的差異：
//是有餘數的除法，餘數一定是>=0
因此除數*商<被除數

int()是直接捨棄尾數，所以在負數的結果會不一樣

如果你有問題的是無條件捨去法的定義：
這邊指的是取floor

**Comment by alemapnil** [comment]
了解
