### ISSUE TITLE
[Week 2] 所有練習

### ISSUE THREAD

**Issue by wenzhichua** [coding-coworking-club/python-2019-fall#6]
## 程式碼

```python

```

## 問題描述

想請問隨堂練習可否不要那麼快關掉呢？回去還想把課堂沒寫出來的完成，希望稍微延長時間 >< 謝謝

**Comment by alexypdu** [comment]
隨堂練習的題目可以在上方 Problems 裡面找到唷！直接搜尋題目名稱即可～

另外這種非程式碼相關的問題下次貼 Facebook 社團就好囉 😉

**Comment by alexypdu** [comment]
如果沒問題的話就先把這個 issue 關掉囉！
