### ISSUE TITLE
[Homework 1] 字元強調

### ISSUE THREAD

**Issue by gg0925** [coding-coworking-club/python-2019-fall#60]
## 提交連結
https://judge.ccclub.io/contest/26/problem/031103

## 程式碼

```python
def a(s):
    if w==w[0]:
        print(s.replace(w,w.upper()))
    else:
        print(s)
    
w=input()
s=str(input())
a(s)
```

## 問題描述

不知道如何解決，若強調的字母不是在字首的問題。
我的想法是if我們所要強調的字是在字首，將其替換成大寫，else就維持原本的樣子

**Comment by sc090410** [comment]
應該說，或許可以想一下不用string.replace()的方法吧！

**Comment by gg0925** [comment]
我再想想!!

**Comment by gg0925** [comment]
學姊能多給我一點提示嗎?
我想了兩個小時還是沒想到
提示就好!

**Comment by sc090410** [comment]
因為字串這種型態不能直接改他的“值”，所以我們最好的方法是產生一個新的字串！像是取原本字串的後半拼上新的字首？或是其他類似這樣產生新字串再放回去的方法～

**Comment by gg0925** [comment]
好的!!!
