### ISSUE TITLE
[General] 第 14 講（更多迴圈）中 Break 範例

### ISSUE THREAD

**Issue by eefish** [coding-coworking-club/python-2019-fall#61]
## 程式碼

```python
prime_list = [2, 3, 5, 7, 9 , 11, 13, 17, 19]
n = int(input())
if n<1 or n >400:
    print('Error')
else:
    isprime = True
    for num in prime_list:
        if n% num == 0 and n !=num:
            isprime = False
            break

            
    if isprime = True:
        print('質數')
    else:
        print('合數')  
```

## 錯誤訊息

  File "<ipython-input-33-3ad1c183ce71>", line 12
    if isprime = True:
               ^
SyntaxError: invalid syntax
## 問題描述

照影片上範例的code打，會出現此錯誤訊息, 好像要改成 isprime==True才能執行
另外影片上是 n% num = 0, 好像要改成 n% num == 0才能執行?
有點不太清楚這裡是要看isprime的值等不等於True/False (用==)
還是要把True/False指定給isprime(用=)

**Comment by hyusterr** [comment]
如果接在 if 後面，通常就是要"判斷"一件事情對不對，這種時候就會用 == ，如果只有一個等於，會變成指定變數喔~
