### ISSUE TITLE
[Homework 1] 字元強調

### ISSUE THREAD

**Issue by Thomas-Ke** [coding-coworking-club/python-2019-fall#62]
## 提交連結
https://judge.ccclub.io/status/820621f20c8ac2a55cf729bd7492e525

## 程式碼

```python
# 請把程式碼填在這！
a=input()
b=input()
a_up=a.upper()
b=b.split(" ")
for i in b:
    c=i[0].replace(a, a_up)
    for j in c:
        b=i.replace(i[0], j)
        print(b, end=" ")
```

## 問題描述
已經可以把字首的部分換成大寫，但是卻沒辦法組回原來的句子，印出來的都只有轉換過後的字首。

**Comment by sc090410** [comment]
因為 `c=i[0].replace(a, a_up)` 這邊的 `c` 就只是你把那個詞的字首抓出來，然後如果是我們要強調的字就改成大寫這樣，所以你 `print(c)` 的時候當然只會輸出字首～
應該要想一下怎麼把其他的部分印出來～

**Comment by Thomas-Ke** [comment]
上面的問題經過修改。c的部分是修改過後的字首，接著是把c取出，再用取出的c換掉i的字首，最後印出b，但是印完後的b沒有改變，不知道哪裡錯了www

**Comment by alexypdu** [comment]
Duplicate of #26 and #28
