### ISSUE TITLE
[Homework 1] 字元強調

### ISSUE THREAD

**Issue by stanleykuo7272** [coding-coworking-club/python-2019-fall#63]
## 提交連結

https://judge.ccclub.io/status/dae12831237651377b95fcd681955aa5

## 程式碼

```python
capital=input()
sentence=input()
sen_sep=sentence.split()
capital_upper=capital.upper
ab="ABCDEFGHIJKLMNOPQRSTVWXYZ"
for i in sentence:
    if i[0] in ab:
        print(sentence.replace(capital,capital_upper()))
```

## 錯誤訊息

wrong answer

## 問題描述

1.  先將數字數入
2. 利用for 迴圈將字串印出
3. 判斷如果是大寫 就將其換成大寫
Ｑ：想了很久 不知道要用什麼方式 才能判斷第一個字換成大寫
有想到一個將不同的字串拆分然後取第一個字，最後再將其組合起來。
但不知道要怎麼下筆。
苦惱很久...

**Comment by sc090410** [comment]
代替苦口婆心的 @alexypdu 回一下，請將程式碼填在這一塊區域裡面～
```
```python
# 請把程式碼填在這！
```
```

**Comment by hyusterr** [comment]
確定一下，你問的是字元數數還是字元強調？

**Comment by oscarcyhsu** [comment]
答案是數字 不是改成大寫的字串喔

**Comment by stanleykuo7272** [comment]
字元強調

**Comment by alexypdu** [comment]
你並沒有通過範例測資二唷。
