### ISSUE TITLE
[Homework 1] 字元強調

### ISSUE THREAD

**Issue by zhanzhiling** [coding-coworking-club/python-2019-fall#64]
https://judge.ccclub.io/status/a51fffec0ef676fd7ec7cc7171adedc2

## 程式碼

```python
emp=input()

s=input()

a=s.split(" ")
b=emp.upper()
for i in a:
    if i[0]==emp:
        
        a[i]=a[i].replace(i[0],b)
        
print(" ".join(a))    
```

## 錯誤訊息

Runtime Error 

## 問題描述

我的想法是找出list中首字母是需要強調的，只換首字母，再把它接起來，不明白是寫法有錯嗎，無法輸出，麻煩助教指導~

**Comment by alexypdu** [comment]
```python
emp=input()

s=input()

a=s.split(" ")
b=emp.upper()
for i in a: # <--- 這裡的 i 是串列 a 裡面一個個的字串，不是 index
    if i[0]==emp:
        
        a[i]=a[i].replace(i[0],b) # <--- a[i] 會出錯
        
print(" ".join(a))    
```

建議先在 Jupyter Notebook 上至少測過範例測資再上傳唷，而且也可以透過錯誤訊息獲得一些線索。

**Comment by zhanzhiling** [comment]
> 
> 
> ```python
> emp=input()
> 
> s=input()
> 
> a=s.split(" ")
> b=emp.upper()
> for i in a: # <--- 這裡的 i 是串列 a 裡面一個個的字串，不是 index
>     if i[0]==emp:
>         
>         a[i]=a[i].replace(i[0],b) # <--- a[i] 會出錯
>         
> print(" ".join(a))    
> ```
> 
> 建議先在 Jupyter Notebook 上至少測過範例測資再上傳唷，而且也可以透過錯誤訊息獲得一些線索。

好的 感謝~我試試~

**Comment by zhanzhiling** [comment]
> ```python
> a[i]=a[i].replace(i[0],b)
> ```

已解決~謝謝助教提醒 i 是string 而不是 index !!
