### ISSUE TITLE
[Homework 1] 字元數數

### ISSUE THREAD

**Issue by Derek459** [coding-coworking-club/python-2019-fall#65]
## 提交連結

https://judge.ccclub.io/contest/26/problem/031105

## 程式碼

```python
s1=input()
s1=s1.split(" ")
s2=input()
s2.count(s1[0]), s2.count(s1[1]), s2.count(s1[2])
```

## 錯誤訊息

Wrong Answer

## 問題描述

jupyter notebook 上面測可以，為什麼批改系統上不行? 
謝謝助教

**Comment by hyusterr** [comment]
記得輸出結果喔，jupyter會自動幫你輸出最後一行是什麼，但批改系統不會~
