### ISSUE TITLE
[Homework 1] 字元強調

### ISSUE THREAD

**Issue by Yi-chunChang** [coding-coworking-club/python-2019-fall#7]
## 提交連結
(找到了)
https://judge.ccclub.io/status/ebc81d3621afb98140a883c581b6a003

## 程式碼

```python
emp=input()
sen=input()
emp_upper = emp.upper()
print (sen.replace(emp, emp_upper))
```

## 錯誤訊息
wrong answer

## 問題描述
judge系統上顯示錯誤但jupyter成功

**Comment by alexypdu** [comment]
我在系統上有看到你的提交唷！你有點進去 contest 後確認右方側邊欄的 submissions 嗎？

**Comment by alexypdu** [comment]
另外程式碼請放到

> \`\`\`python
> 
> \`\`\`

裡面唷 🙏

**Comment by Yi-chunChang** [comment]
都修改好了，麻煩了，謝謝。

**Comment by alexypdu** [comment]
提交連結應該是一個超連結 🔗 唷（可以按右鍵複製），請不要只提供流水號，我們很難搜尋 😅

**Comment by Yi-chunChang** [comment]
不好意思，我改好了，不知道這樣可不可以，感謝。

**Comment by alexypdu** [comment]
你第二筆範例測資有過嗎？

**Comment by Yi-chunChang** [comment]
有耶，在jupyter上有成功跑出來~

**Comment by Yi-chunChang** [comment]
![_n](https://user-images.githubusercontent.com/55389956/65014313-e0954200-d950-11e9-9df1-412a4cfac645.jpg)

**Comment by Kevinweisl** [comment]
只有每個詞的第一個字元是我們要強調的那個，才會轉成大寫喔。

**Comment by alexypdu** [comment]
你要不要跟題目的 `Sample Output 2` 仔細比對一下 👀

**Comment by Yi-chunChang** [comment]
我有發現差異，我想說題目上沒有標示第一個字元，我再試試看，感謝~
