### ISSUE TITLE
[General] 7-1：長方星

### ISSUE THREAD

**Issue by snow567** [coding-coworking-club/python-2019-fall#71]
## 提交連結

https://judge.ccclub.io/status/6b87c9d1129cb0996aa4d070313e123e

## 程式碼

```python
# 請把程式碼填在這！
l=int(input())
w=int(input())
for i in range(w):
    print()
    for j in range(l):
        print("*",end="")
```

## 問題描述

在jupyter測試範例中有通過，請問為何在judge中會是Wrong Answer

**Comment by hyusterr** [comment]
你現在的程式碼跑出來的會是(以輸入4 3)為例：
![image](https://user-images.githubusercontent.com/52968111/65830660-053fd100-e2e4-11e9-8843-0a293b440295.png)
其中，第一行是一個空行(只包含一個換行符)，所以才會導致WA
想想怎麼解決這種情況，答案應該就出來了~

**Comment by snow567** [comment]
問題已解決，謝謝助教
