### ISSUE TITLE
[Homework 1] 字元數數

### ISSUE THREAD

**Issue by wenwen-17** [coding-coworking-club/python-2019-fall#72]
## 提交連結
https://judge.ccclub.io/status/8038e41b9bea204d660ad2c7eb154d74

## 程式碼

```python
n=input()
n_split=n.split()
lst=input()
for i in n_split:
    count=0
    for k in lst:
        if k == i:
            count+=1
    print(count, end=" ")
```

## 錯誤訊息

Wrong Answer

## 問題描述

用sample 1 測試時答案是正確的，但用sample 2測試時output 卻是4 3 2，自己看不出哪裡有問題，請大神們幫幫忙><謝謝

**Comment by sc090410** [comment]
大小寫都算哦
