### ISSUE TITLE
[Homework 1] 數字相加

### ISSUE THREAD

**Issue by xinyo0229** [coding-coworking-club/python-2019-fall#73]
## 程式碼

```python
a=int(input())+int(input())
print(a)
```

## 錯誤訊息

Runtime Error
Time: 24ms Memory: 8MB Lang: Python3 Author: klove81229

## 問題描述

根據我的程式碼，提供的範例都可以得到正確的結果，但是批改系統上，一直不被接受QQ麻煩解惑，謝謝。

**Comment by hyusterr** [comment]
請將程式碼提交在指定範圍中，你的格式跑掉了

**Comment by xinyo0229** [comment]
不好意思，不太懂格式的意思是?謝謝。

**Comment by hyusterr** [comment]
此外能否提供你的提交連結呢？

**Comment by xinyo0229** [comment]
https://judge.ccclub.io/contest/26/problem/031101

**Comment by hyusterr** [comment]
> 不好意思，不太懂格式的意思是?謝謝。

請參考提交範例喔

**Comment by hyusterr** [comment]
輸入只有一行喔，你確定你有通過範例了嗎？

**Comment by xinyo0229** [comment]
> 輸入只有一行喔，你確定你有通過範例了嗎？

我發現是可以輸出正確結果的@@謝謝。

![image](https://user-images.githubusercontent.com/55389812/65831268-6e2a4780-e2ea-11e9-852f-6325435ccf63.png)

**Comment by hyusterr** [comment]
![image](https://user-images.githubusercontent.com/52968111/65832602-7be6c980-e2f8-11e9-8cc0-cbe617ac01ef.png)
這個東西叫做
8(空格)9
而不是有兩個輸入
8
9
喔
你確定你有通過範例資料嗎？

**Comment by yayuncheng** [comment]
我的這題也怪怪的，有輸入一行為 8 9 , 輸出一行相合為 17

提交連結: https://judge.ccclub.io/status/8bbf9c3f155169188fcdd45ce173f21e

錯誤訊息: Wrong Answer

我還是沒有通過測驗 麻煩助教指點了 謝謝!

**Comment by hyusterr** [comment]
喔喔 題目要輸出的是整數 不是浮點數喔

**Comment by yayuncheng** [comment]
> 喔喔 題目要輸出的是整數 不是浮點數喔

謝謝提醒!

**Comment by xinyo0229** [comment]
> ![image](https://user-images.githubusercontent.com/52968111/65832602-7be6c980-e2f8-11e9-8cc0-cbe617ac01ef.png)
> 這個東西叫做
> 8(空格)9
> 而不是有兩個輸入
> 8
> 9
> 喔
> 你確定你有通過範例資料嗎？

了解了，謝謝助教的提醒，辛苦了，謝謝。
