### ISSUE TITLE
[Homework 1] 大小寫互換

### ISSUE THREAD

**Issue by xinyo0229** [coding-coworking-club/python-2019-fall#74]
## 程式碼

```python
a=input()
print(a.upper())
```

## 問題描述

我在jupyter notebook中都可以輸出範例結果，但是在批改系統中，一直無法被接受，請問如何解決呢?辛苦了，謝謝。
![image](https://user-images.githubusercontent.com/55389812/65831451-1d1b5300-e2ec-11e9-86e3-24829c1fa5a1.png)

**Comment by hyusterr** [comment]
有可能是全部大寫轉成小寫喔，請再看清楚題目~

**Comment by xinyo0229** [comment]
> 有可能是全部大寫轉成小寫喔，請再看清楚題目~

好的，不好意思沒注意清楚，謝謝提醒。
