### ISSUE TITLE
[Homework 1] 字元強調

### ISSUE THREAD

**Issue by lisa9477** [coding-coworking-club/python-2019-fall#76]
## 程式碼

```python
# 請把程式碼填在這！
word=input()
sentence=[i for i in input().split(" ")]
word2=word.upper()

for j in range (len(sentence)):
    if sentence[j][0]==word:
        sentence[j][0].replace(word,word2)
    
result=" ".join(sentence)
print(result)

```

## 問題描述

我是想說直接把每個字的字首，如果符合條件的話，就直接換成大寫，但是輸出的答案都沒變
不知道錯在哪裡QQ

**Comment by hyusterr** [comment]
1. replace是對一整個字串裡的所有這個字元做取代
2. 要記得把取代完之後的結果存進sentence相應的位置喔

**Comment by lisa9477** [comment]
1. 我以為sentence[j][0]就是指第一個字的位置而已?
2. 但當我把"sentence[j][0].replace(word,word2)"改成"sentence[j][0]==word2"的話，我以為就是存回去的意思? 但是結果還是沒改變QQ

**Comment by hyusterr** [comment]
1. 沒錯
2. == 是判斷等不等於的意思，並不是 assign
3. 字串沒辦法用item assignment的方式替換裡面的字元
4. 你可以試著用 print 來 debug 也許會更懂卡在哪裡喔

**Comment by lisa9477** [comment]
了解了~謝謝助教~

**Comment by lisa9477** [comment]
懂了! 謝謝助教~
