### ISSUE TITLE
[Homework 1] 字元強調

### ISSUE THREAD

**Issue by lss19920912** [coding-coworking-club/python-2019-fall#80]
## 程式碼

```python
# 
letter1 = input()
letter2 = letter1.upper()
sentence1  = input()
sentence2 = sentence1.title()
lst_sentence2 = list(sentence2)
lst_sentence1 = list(sentence1)
for i in range(len(lst_sentence2)) :
    if lst_sentence2[i] != letter2 and lst_sentence1[i] != lst_sentence2[i] :
        lst_sentence2[i] = lst_sentence2[i].lower()
print("".join(lst_sentence2))

```

## 問題描述

抱歉我作業晚交，因為第四題一直寫不出來，剛剛終於寫出OK的結果，但已經超時無法上傳來確認是不是寫對了，如果可以的話，能不能請助教幫我看看這樣寫對不對，求知慾讓我迫切想證明我寫的是對的嗚嗚嗚

**Comment by sc090410** [comment]
嗨我把作業一開在problems了！你可以去 [這邊](https://judge.ccclub.io/problem/193103) 測測看，有問題再問我們～

**Comment by lss19920912** [comment]
> 嗨我把作業一開在problems了！你可以去 [這邊](https://judge.ccclub.io/problem/193103) 測測看，有問題再問我們～

助教您好，我已經測過，是說wrong answer， 但是我試過很多的句子跑出來都是對的耶，不知道問題出在哪，能不能請助教幫我看看，謝謝您～

**Comment by alexypdu** [comment]
@lss19920912 麻煩提供提交連結

**Comment by lss19920912** [comment]
> @lss19920912 麻煩提供提交連結

這邊是我的連結，謝謝助教
https://judge.ccclub.io/status/1373dd3ac5ba43e340fd934c5d0ddb9b
