### ISSUE TITLE
[General] 9-1：數字總和排序

### ISSUE THREAD

**Issue by emily41127** [coding-coworking-club/python-2019-fall#84]
## 提交連結

https://judge.ccclub.io/status/48ad9a9fb7ece2649f3ca434ceb62496

## 程式碼

```python
# 請把程式碼填在這！
def total(s):
    a = 0
    for i in s:
        a += int(i)
    return str(int(a)).strip('')

nums = input().split(" ")
print(list(map(int , sorted(nums , key=total))))
```

## 問題描述

在jupyter notebook上測試兩個答案都是相同的，可是放到judge系統上就顯示wrong answer
本來以為是資料型態的問題，後來把資料型態改成int之後，仍舊顯示wrong answer
想請問是否有其他邊際案例嗎QQ?

**Comment by alexypdu** [comment]
試試這個：

```
2 92
```

**Comment by alexypdu** [comment]
關於字串如何比大小：https://github.com/coding-coworking-club/python-2019-fall/issues/46#issuecomment-535040142

**Comment by emily41127** [comment]
試了好久都沒辦法把list裡面的東西變成int
## 程式碼


```python
# 請把程式碼填在這！
def total(s):
    a = 0
    for i in s:
        a += int(i)
    return a

nums = list(map(int(input().split(" "))))
sorted(nums, key=total)
nums = list(map(int, nums))
print(nums)```

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

**Comment by hyusterr** [comment]
可以試試看上課教的 list comprehension！

**Comment by hyusterr** [comment]
然後用map也可以，但map的用法是
http://www.runoob.com/python/python-func-map.html

**Comment by emily41127** [comment]
之前有試過了QQ
可是出來也是TypeError: 'int' object is not iterable
```python
# 請把程式碼填在這！
def total(s):
    a = 0
    for i in s:
        a += int(i)
    return int(a)

lst = [int(num) for num in input().split(" ")]
sorted(lst , key=total)
nums = list(map(int, nums))
print(nums)```

**Comment by alexypdu** [comment]
```python
def total(s): # <-- function total 拿到的 s 會是串列 lst 裡面一個個的「整數」
    a = 0
    for i in s: # <--- 整數是不能遍歷（iterate）的，就是不能對它跑 loop
        a += int(i)
    return int(a)

lst = [int(num) for num in input().split(" ")]
sorted(lst , key=total)
nums = list(map(int, nums))
print(nums)
```

**Comment by emily41127** [comment]
所以是要在他跑完之後再轉換成整數，然後再用sorted來判別嗎??

**Comment by alexypdu** [comment]
如果是我的話實作邏輯大概會像下面這樣：

```python
def total(num): 
# do something

lst = [int(_) for _ in input().split()]
print(sorted(lst, total))
```

**Comment by emily41127** [comment]
可是這樣的話，不是代表輸入的lst變成一個一個的整數，最後又變成整數去跑loop了嗎?
((但是整數不能遍歷（iterate），就是不能對它跑 loop????))

**Comment by alexypdu** [comment]
你可能要查一下 `sorted()` 這個 function 的第二個參數（這裡的 `total()`）是在幹嘛唷。

**Comment by emily41127** [comment]
這裡的`total()`是排序的規則，所以代表要跑上面自訂的程式，可是我上面的程式有loop，所以是上面的定義程式不應該使用loop的意思嗎QQ?

**Comment by sc090410** [comment]
作為sorted的key function會自動幫你計算出list中每個element的這個total的回傳值，然後幫你依照這些回傳值排序。所以 total 這個function只需要針對“element”來寫即可。
建議可以看一下這個第二段：“Python 初學第十講 — 排序” https://link.medium.com/Grr75nC0p0

**Comment by emily41127** [comment]
我上面寫的`def`是用字串中的某個數字來加，再回傳給`sorted()`排序，可是系統是說型態不能使用`int()`，還是我哪裡理解錯誤了QQ??
想了很久還是想不出來QQ

**Comment by alexypdu** [comment]
看到你提交過了，先關掉囉。

**Comment by emily41127** [comment]
@alexypdu 助教我不能reopen XDDD

**Comment by emily41127** [comment]
@alexypdu 可以了!!謝謝你!!
