### ISSUE TITLE
[General] 6-2：完全平方數

### ISSUE THREAD

**Issue by QuintusZhan** [coding-coworking-club/python-2019-fall#88]
## 提交連結

https://judge.ccclub.io/status/fcc8f5657dba88549dc74089928ad432

## 程式碼

```python
import math
a=math.sqrt(int(input()))
for i in range(1,int(a)):
    print(i ** 2)
```

## 錯誤訊息

Wrong Answer

## 問題描述

批改系統可以用import嗎，不然自己試的，都可以跑出想要的結果

**Comment by hyusterr** [comment]
import 內建函式庫是沒問題的喔

**Comment by hyusterr** [comment]
另外，想想看你的作法在input
111
的時候，為什麼沒有輸出100呢？
