### ISSUE TITLE
[General] 11-2：字串字典

### ISSUE THREAD

**Issue by wenzhichua** [coding-coworking-club/python-2019-fall#89]
## 提交連結

https://judge.ccclub.io/status/9f821d20457d7ac9b2c35e636a81b8c1

## 程式碼

```python
# 請把程式碼填在這！
word=input()
word=word.lower()
alphabet='abcdefghijklmnopqrstuvwxyz'

d={i: word.count(i) for i in alphabet if word.count(i)>0 }
i=1
for key, value in d.items():
  if i<len(d):
    print(key, value, sep='', end=' ')
    i +=1
  else:
    print(key, value, sep='',end='')
```

## 錯誤訊息

wrong answer

## 問題描述

測試答案是對的～ 最後也沒有多餘的空格
找不到哪裡錯> <
希望能指點迷津

**Comment by alexypdu** [comment]
```python
for key, value in d.items():
```

在 Python 3.5（批改系統上的 Python 版本）中，這裡拿出來的 `key` `value` 不會按照你放進字典的順序取出唷 ！然後你在 Jupyter Notebook 上可能會看到正確的行為是因為 Python 3.7 之後有保證取出順序等於放入順序了（優化）。

字典本身應該是一個 unordered（無順序的）的資料結構，希望同學們可以記住這點，也算本題的小陷阱，請利用其他有順序的資料結構來輔助吧！

**Comment by wenzhichua** [comment]
原來！！謝啦～～
