### ISSUE TITLE
[Homework 1] 大小寫互換

### ISSUE THREAD

**Issue by emily41127** [coding-coworking-club/python-2019-fall#9]
## 程式碼

```python
# 請把程式碼填在這！
noun=input()
voc="abcdefghijklmonpqrstuvwxyzABCDEFGHIJKLMONPQRSTUVWXYZ"
voc1="abcdefghijklmonpqrstuvwxyz"
for voc in noun:
    if voc1 in noun:
        print(noun.upper())
        break
    else:
        print(noun.lower())
        break
```

## 問題描述

小寫無法轉換大寫。

**Comment by alexypdu** [comment]
現在假設輸入只有一個小寫字元 `a`，能不能試著說出你的程式從開始到結束每一行會做什麼事情？

**Comment by emily41127** [comment]
noun=input()   #輸入a
voc="abcdefghijklmonpqrstuvwxyzABCDEFGHIJKLMONPQRSTUVWXYZ"
voc1="abcdefghijklmonpqrstuvwxyz"
for voc in noun:  #判別a在voc內，因此進入for迴圈
    if voc1 in noun:  #如果a在voc1裡面，跑下面的程式，因為在voc1裡面，所以跑下面的程式
        print(noun.upper()) #輸出(大寫的noun)
        break #結束迴圈
    else:
        print(noun.lower())
        break
我的想法大概是這樣子。是哪裡理解錯惹嗎QQ??

**Comment by alexypdu** [comment]
先澄清一下你的敘述：

```python
for voc in noun: # 判別 noun 在 voc 內，因此進入 for 迴圈 <--- 這句話是不對的
```

for 迴圈並不會有判斷的行為，而是會直接重複執行某段程式碼，你可以再複習一次線上課程有關迴圈的部分。

```python
if voc1 in noun: # 因為 a 在 voc1 裡面，所以跑下面的程式 <--- 這句話也是不對的
```
在只有 `a`  一個字元的時候，`noun in voc1` 會是 `true` 沒錯，但如果輸入是 `ccClub` 則 `noun in voc1` 會是 `false`，因為 `ccClub` 並不是 `abcdefghijklmonpqrstuvwxyz` 的子字串。

**Comment by alexypdu** [comment]
如果你的問題已經解決的話再請你點選下方的 **Close issue** 喔！

**Comment by LAIYANLIANG** [comment]
你好~
請問這題的重點在else if的運用嗎？？
因為有看到其他函數的答案可以直接作

**Comment by alexypdu** [comment]
~~同學破梗了~~ 對唷，一開始希望能加強你們對條件判斷的熟悉度 😎

**Comment by LAIYANLIANG** [comment]
好的，謝謝呢~

**Comment by emily41127** [comment]
喔喔喔xDD我知道惹，謝謝。
