### ISSUE TITLE
[General] 9-1：數字總和排序

### ISSUE THREAD

**Issue by Frank-Jiang-from-TW** [coding-coworking-club/python-2019-fall#91]
## 提交連結

https://judge.ccclub.io/status/828402324b274d0d87002ab983c9f291

## 程式碼

```python
def sum_num(n):
    sum = 0
    for i in range(len(n)):
        sum += int(n[i])
    return str(sum)

n=input().split()
n=sorted(n,key=sum_num)
print("[",end="")
for i in range(len(n)-1):
    print(n[i], end=", ")
print(n[-1],end="]")
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/55695230/66257975-303d8f80-e7d2-11e9-9018-30d2c5c5d010.png)
![image](https://user-images.githubusercontent.com/55695230/66257995-709d0d80-e7d2-11e9-9ec7-89dddec3e4f3.png)

## 問題描述

不知道為什麼不給過，總之就是排序嘛，最後為了讓輸出結果沒有引號，所以分了三段輸出，不知道這樣錯誤在哪

**Comment by alexypdu** [comment]
Duplicate of #84

**Comment by Frank-Jiang-from-TW** [comment]
過了~感謝~
我把第5行的str()拿掉就可以了
我忘記我當初為什麼要把它改成字串了
