### ISSUE TITLE
[General] 綜合1-2：一奇多偶

### ISSUE THREAD

**Issue by wenzhichua** [coding-coworking-club/python-2019-fall#92]
## 提交連結 

https://judge.ccclub.io/status/157aecb32a5c668632c830b10a78472b

## 程式碼

```python
# 請把程式碼填在這！
a=input()
listA= a.split(' ')
number=[ i for i in set(listA)]

for j in number:
  if listA.count(j)%2!=0:
    print(j)
    break
  else:
    continue
```

## 錯誤訊息

WRONG ANSWER

## 問題描述

先把input弄成list，再弄成set，用set去找出現奇數次的數字，找到後就印出來然後break。
測試範例是對的，感覺應該是忽略了一個重要的概念，懇求指教～～

**Comment by alexypdu** [comment]
第二行要改成 `listA= a.split()`，然後應該會變成 **Time Limit Exceeded**，你要想一下怎麼加速你的程式。
