### ISSUE TITLE
[General] 9-1：數字總和排序

### ISSUE THREAD

**Issue by William00717** [coding-coworking-club/python-2019-fall#93]
## 提交連結

https://judge.ccclub.io/status/859fe6e5dfef9552ec002257444035b7

## 程式碼

```python
# def total(a):
     count = 0
     for i in a:
            for j in i:
                count += int(j)
     return count
            
a=input().split(" ")
a=sorted(a, key=total)
print(a)
```

## 問題描述

我已經能依照數字總和排序字串了，但對比了範例的output，發現我無法將字串前後的''去除，因此得到了Wrong Answer的結果。所以想要請問助教們，我應該如何修正呢？謝謝！

**Comment by alexypdu** [comment]
Duplicate of #84 and #87

**Comment by William00717** [comment]
助教 您好：
謝謝您所指引的兩篇問題，但還是有些看不太懂，最後試著參照#91這篇，將輸出格式分段輸出，成功解決問題。
