### ISSUE TITLE
[General] 9-1：數字總和排序

### ISSUE THREAD

**Issue by rose020** [coding-coworking-club/python-2019-fall#94]
## 程式碼

```python
def f(s):
    total=0
    s=list(s)
    for i in range(len(s)) :
        total+=int(s[i])
        return total
    
a=input().split()
b=list(map(int,a)) 
map(f(s),b)
a=sorted(a,key=total)
print(list(map(int,a))) 

```

## 問題描述
我試了很多例子都成功排序，程式也可以跑，就是不知道為什麼不通過呢？

**Comment by Peterorr** [comment]
錯誤訊息是？
另外，能提供你的「提交連結」嗎？

**Comment by rose020** [comment]
程式可以跑所以沒有錯誤訊息
https://judge.ccclub.io/problem/180024
謝謝～

**Comment by jeffery12697** [comment]
後面可以說一下思路嗎～有點看不懂ＱＱ
我前面看到的問題是def的return要跟for對齊噢～不然for迴圈跑不完就return了

**Comment by rose020** [comment]
我自己再看一次也看不懂了......
所以我又再按照現在的思路打了一遍
程式可以跑
兩個例子也都對
可是就是顯示不通過
可以請助教幫我看看嗎謝謝
[https://judge.ccclub.io/status/cfb821cbed8060e55b538861edf3dccf](url)

**Comment by rose020** [comment]
我再看一次也看不懂自己在寫什麼了......
我用現在的想法再寫了一次
在Jupyter Notebook程式可以跑答案輸出也沒有問題
可是到提交作業的地方就跑不動了
請問我哪裡寫錯了呢
[https://judge.ccclub.io/status/9c82b37b5e0170e9cbdabbcf8a4e726e](url)

**Comment by alexypdu** [comment]
```python
def num(s):
    total=0
    for i in s :
        total+=int(i)
    return total
    
a=input().split()
b=list(map(f,a)) # <--- what's this f here?
a=sorted(a,key=num)
print(list(map(int,a)))
```

**Comment by rose020** [comment]
打錯了！謝謝助教～已通過
