### ISSUE TITLE
[General] 最大公因數(迴圈vs函式的差別)

### ISSUE THREAD

**Issue by eefish** [coding-coworking-club/python-2019-fall#95]
## 程式碼

```python
a = int(input())
b = int(input())

if a>b:
    smaller=b
else:
    smaller=a
    
for i in range(smaller, 0, -1):
    if a%i ==0 and b%i==0:
        max=i
        break
print (max)

def gcd(a,b):
    if a>b:
        smaller=b
    else:
        smaller=a
    
    for i in range(smaller, 0, -1):
        if a%i ==0 and b%i==0:
            return i
a = int(input())
b = int(input())
print(gcd(a, b))
```

## 問題描述

為何使用loop時(上半部的code)，會需要一個break才能將最大公因數print出(不然會回傳所有的公因數)。但寫成函式時(下半部的code)，卻可以直接回傳最大公因數，不會回傳其他公因數？

**Comment by alexypdu** [comment]
上半部的迴圈如果把 `break` 應該會印出 `1` 吧，因為迴圈會完整跑完。
下半部函式的部分在迴圈當中如果遇到 `return` 就會直接結束函式的執行並把當下的 `i` 拋出來了。
這也是為什麼你上半部的迴圈中要有 `break` 才會得正解的原因。

**Comment by eefish** [comment]
我指的是像下面這樣的code
不過我了解了，謝謝!

a = int(input())
b = int(input())

if a>b:
    smaller=b
else:
    smaller=a
    
for i in range(smaller, 0, -1):
    if a%i ==0 and b%i==0:
        print(i)
